[build-system]
requires = ["setuptools>=65.6.3"]
build-backend = "setuptools.build_meta"

[project]
name = "geometry_vs_topography"
version = "1.0.0"
description = "Code needed to reproduce findings from geometry vs. topography paper"
readme = "README.md"
authors = [{ name = "Bogdan Petre", email = 'f0042vm@dartmouth.edu'}, { name = "Martin A. Lindquist", email = 'mlindqui@jhsph.edu'}, { name = "Tor D. Wager", email = 'Tor.D.Wager@dartmouth.edu'}]

[project.entry-points."console_scripts"]
pairwise_parcel_op = 'geometry_vs_topography.pairwise_parcel_op:main'