% this code was generated by chatGPT using the following prompt:
%{
I need a matlab function that takes the following input

faces - an m x 3 matrix of surfaces. Each row is numeric and indicates the numeric labels of three nodes in a graph that are connected. Collectively the elements of faces defines a (possibly disconnected) 3d mesh.
tri - n x 3 matrix of x y and z coordinates which for each row i defines the location in 3d space of the index labeled by i. These indices i are the same indices indicated by the faces matrix above.
cdata - an n x 1 binary vector.

I want this function to return a new binary vector which contains only exterior points of regions from cdata that are contiguous on the 2d mesh defined by faces and and triangles provided.

please give me a solution that only uses code from the standard matlab toolbox
%}
% I then followed with
%{
    ok now return code that does the same thing but also returns every direct neighbor of the exteriorPoints together with the exterior points
%}

function [exteriorPoints, allRelevantPoints] = findExteriorPoints(faces, tri, cdata)
    % Number of points
    nPoints = size(tri, 1);
    
    % Create adjacency list for the points based on faces
    adjacencyList = cell(nPoints, 1);
    for i = 1:size(faces, 1)
        adjacencyList{faces(i, 1)} = unique([adjacencyList{faces(i, 1)} faces(i, 2) faces(i, 3)]);
        adjacencyList{faces(i, 2)} = unique([adjacencyList{faces(i, 2)} faces(i, 1) faces(i, 3)]);
        adjacencyList{faces(i, 3)} = unique([adjacencyList{faces(i, 3)} faces(i, 1) faces(i, 2)]);
    end

    % Find connected components using DFS
    visited = false(nPoints, 1);
    components = zeros(nPoints, 1);
    componentIndex = 0;

    % Helper function to perform DFS
    function dfs(v, index)
        stack = [v];
        while ~isempty(stack)
            node = stack(end);
            stack(end) = [];
            if ~visited(node)
                visited(node) = true;
                components(node) = index;
                % Add non-visited neighbors to the stack
                neighbors = adjacencyList{node};
                for neighbor = neighbors
                    if ~visited(neighbor) && cdata(neighbor)
                        stack(end + 1) = neighbor;
                    end
                end
            end
        end
    end

    % Execute DFS to label components
    for i = 1:nPoints
        if ~visited(i) && cdata(i)
            componentIndex = componentIndex + 1;
            dfs(i, componentIndex);
        end
    end
    
    % Determine exterior points and collect their neighbors
    exteriorPoints = false(nPoints, 1);
    allRelevantPoints = false(nPoints, 1);
    for i = 1:nPoints
        if cdata(i) && components(i) ~= 0
            % Check all neighbors of i
            neighbors = adjacencyList{i};
            isExterior = false;
            for neighbor = neighbors
                if components(neighbor) ~= components(i)
                    isExterior = true;
                    break;
                end
            end
            if isExterior
                exteriorPoints(i) = true;
                allRelevantPoints(i) = true;
                % Include all direct neighbors of the exterior point
                allRelevantPoints(neighbors) = true;
            end
        end
    end
end
