% Before running this script make sure that
% task_topographic_similarities.mat and rsn_topographic_similarities.mat
% are available in the current working directory. These can be generated by
% - prepare_task_topographic_similarities.m
% - prepare_rsn_topographic_similarities.m

close all; clear all;

config = jsondecode(fileread('../../config.json'));

addpath(config.matlab_libraries.spm12);
addpath(genpath(config.matlab_libraries.cifti_matlab));
addpath(genpath(fullfile(config.matlab_libraries.canlabCore, 'CanlabCore')));

addpath('../../matlab_libraries');
addpath('../../resources/neuromaps');

fontsize=config.matlab_disp_scheme.fontsize;

f = figure;
cm = colormap(f,'hot');
close(f)

dc_color = config.matlab_disp_scheme.color_main;
dc_color_light = config.matlab_disp_scheme.color_light;

unrestricted = readtable(config.hcp_participant_data.unrestricted);
restricted = readtable(config.hcp_participant_data.restricted);
n_subj = height(restricted);

perm = 5000;

data_root = '../../derivatives/hcp_glm_msmall_grayord_spm/';
rsn_root = '../../derivatives/restingstate/hcp25/';

noise='whitened';
%% ACE model design
ACE = [1,1,0,0,1;...
    0.5,1,0,0,1;...
    0.5,0,1,0,1;...
    0.25,0,0,1,1;...
    0,0,0,0,1];

DCE = [1,1,0,0,1;...
    0.25,1,0,0,1;...
    0.25,0,1,0,1;...
    0,0,0,1,1;...
    0,0,0,0,1];

ACDE = [1,1,1,0,0,1;...
    0.5,0.25,1,0,0,1;...
    0.5,0.25,0,1,0,1;...
    0.25,0,0,0,1,1;...
    0,0,0,0,0,1];

%% import atlas in cifti space and get region names
atlas_cii = cifti_read(config.canlab2024.path);
atlas_labels = atlas_cii.diminfo{2}.maps.table(2:end); % drop first label, it corresponds to 0-valued vertices, i.e. the medial wall
roi_labels = {atlas_labels.name}; 

atlas_cii = get_cifti_data(config.canlab2024.path);
n_roi = length(unique([atlas_cii.cortex_left, atlas_cii.cortex_right, atlas_cii.volumes])) - 1;

%% get family clusters

% get all within family mz relationsips
[female, age, income, education] = deal(nan(height(restricted),1));
race = cell(height(restricted),1);
[non_gt_twin, hs, fs, dz, mz, mz_gt, dz_gt, mz_sr, dz_sr] = deal(false(height(restricted)));
for i = 1:height(restricted)
    this_sid = restricted.Subject(i); 
    family_ind = restricted.Father_ID == restricted.Father_ID(i) & restricted.Mother_ID == restricted.Mother_ID(i);
    
    age(i) = restricted.Age_in_Yrs(i);
    female(i) = ~strcmp(unrestricted.Gender{unrestricted.Subject == this_sid}, 'M');
    income(i) = restricted.SSAGA_Income(i);
    education(i) = restricted.SSAGA_Educ(i);
    if strcmp(restricted.Ethnicity(i),'Hispanic/Latino')
        race(i) = {'Hispanic/Latino'};
    else
        race(i) = restricted.Race(i);
    end
    
    switch restricted.ZygositySR{i}
        case 'NotTwin'
            [fs(i, family_ind), fs(family_ind, i)] = deal(true);
        case {'MZ', 'NotMZ'}
            switch restricted.ZygosityGT{i}
                case 'MZ'
                    twin_ind = find((strcmp(restricted.ZygosityGT, 'MZ') | strcmp(restricted.ZygositySR, 'MZ')) ...
                        & family_ind);
                    %twin_ind = find(strcmp(restricted.ZygosityGT, 'MZ') & family_ind);
                    [mz(i, twin_ind), mz(twin_ind,i), mz_gt(i,twin_ind), mz_gt(twin_ind,i)] = deal(true);

                    nontwin_sib = find(~strcmp(restricted.ZygosityGT, 'MZ') & ~strcmp(restricted.ZygositySR, 'MZ') ...
                        & family_ind);
                    [fs(i, nontwin_sib), fs(nontwin_sib, i)] = deal(true);
                case 'DZ'
                    twin_ind = find((strcmp(restricted.ZygosityGT, 'DZ') | strcmp(restricted.ZygositySR, 'NotMZ')) & ...
                        family_ind);
                    %twin_ind = find(strcmp(restricted.ZygosityGT, 'DZ') & family_ind);
                    [dz(i, twin_ind), dz(twin_ind,i), dz_gt(i,twin_ind), dz_gt(twin_ind,i)] = deal(true);

                    nontwin_sib = find(~strcmp(restricted.ZygosityGT, 'DZ') & ~strcmp(restricted.ZygositySR, 'NotMZ') ...
                        & family_ind);
                    [fs(i, nontwin_sib), fs(nontwin_sib, i)] = deal(true);
                otherwise
                    switch restricted.ZygositySR{i}
                        case 'MZ'
                            twin_ind = find(strcmp(restricted.ZygositySR, 'MZ') & family_ind);
                            %[non_gt_twin(i, twin_ind), non_gt_twin(twin_ind,i)] = deal(true);
                            [mz(i, twin_ind), mz(twin_ind,i), mz_sr(i,twin_ind), mz_sr(twin_ind,i)] = deal(true);
            
                            nontwin_sib = find(~strcmp(restricted.ZygositySR, 'MZ') & family_ind);
                            [fs(i, nontwin_sib), fs(nontwin_sib, i)] = deal(true);
                        case 'NotMZ'
                            twin_ind = find(strcmp(restricted.ZygositySR, 'NotMZ') & family_ind);
                            %[non_gt_twin(i, twin_ind), non_gt_twin(twin_ind,i)] = deal(true);
                            [dz(i, twin_ind), dz(twin_ind,i), dz_sr(i,twin_ind), dz_sr(twin_ind,i)] = deal(true);
            
                            nontwin_sib = find(~strcmp(restricted.ZygositySR, 'NotMZ') & family_ind);
                            [fs(i, nontwin_sib), fs(nontwin_sib, i)] = deal(true);
                    end
                    fprintf('Subject %d is missing genotypically identified data. GR entry: %s\n', restricted.Subject(i), restricted.ZygosityGT{i});
            end
        otherwise
            fprintf('Subject %d has unexpected self reported zygosity: %s\n', restricted.Subject(i), restricted.ZygositySR{i});
    end

    half_sib = find(xor(restricted.Mother_ID == restricted.Mother_ID(i), restricted.Father_ID == restricted.Father_ID(i)));
    [hs(i, half_sib), hs(half_sib, i)] = deal(true);
end

hs = hs & ~eye(height(restricted));
fs = fs & ~eye(height(restricted));
dz = dz & ~eye(height(restricted)); 
mz = mz & ~eye(height(restricted));

unr = ~hs & ~fs & ~mz & ~dz & ~non_gt_twin & ~eye(height(restricted));

mz_gt = mz_gt & ~eye(height(restricted));
mz_sr = mz_sr & ~eye(height(restricted));
dz_gt = dz_gt & ~eye(height(restricted));
dz_sr = dz_sr & ~eye(height(restricted));


%% load exhaustive cosine similarities and goemetric similarities of tasks
load(sprintf('task_topographic_similarities_%s.mat', noise),'roi_topo','good_topo');

geom_bsc = dir(fullfile(data_root,sprintf('bsc_all/%s_betas/cosine/*v_all.tsv',noise)));
roi_geom0 = zeros(length(geom_bsc),length(geom_bsc),518);
for i = 1:length(geom_bsc)
    csv = readmatrix(fullfile(geom_bsc(i).folder, geom_bsc(i).name),'FileType','text');
    [roi_geom0(i,(i+1):end,:), roi_geom0((i+1):end,i,:)] = deal(csv);
    roi_geom0(i,i) = 1;
end

% check for correspondence between roi_topo and roi_geom
geom_sid = arrayfun(@(x1)(str2double(strrep(x1.name,'_v_all.tsv',''))), geom_bsc);
topo_sid = unrestricted.Subject(good_topo);
for i = 1:length(geom_sid)
    assert(geom_sid(i) == topo_sid(i));
end

% expand roi_geom to match topo_roi (and more importantly restricted)
roi_geom = nan(size(roi_topo));
roi_geom(good_topo, good_topo,:) = roi_geom0;
clear roi_geom0

%% trival renaming for legacy code reuse
topo_r = roi_topo;
geom_r = roi_geom;

mean_topo_r = nanmean(topo_r,3);
mean_geom_r = nanmean(geom_r,3);

%% print subject counts
% this information is used to population demographic tables

n_mz = sum(sum(mz.*~isnan(topo_r(:,:,1))) > 0)
n_mz_dyads = sum(mz(:).*~isnan(mean_topo_r(:)))/2

n_mz_gt = sum(sum(mz_gt.*~isnan(topo_r(:,:,1))) > 0)
n_mz_gt_dyads = sum(mz_gt(:).*~isnan(mean_topo_r(:)))/2

is_an_mz_twin = sum(mz.*~isnan(topo_r(:,:,1))) ~= 0;

% mz age
mz_age_mean = mean(age(is_an_mz_twin))
mz_age_sd = std(age(is_an_mz_twin))

% mz sex
mz_n_female = sum(female(is_an_mz_twin))/sum(is_an_mz_twin)

% mz income
mz_income = sort(income(is_an_mz_twin));
[a,b] = unique(mz_income(~isnan(mz_income)));
mz_income_bracket_counts = [a,[diff(b); length(mz_income)-b(end)]/length(mz_income)*100]
unreported_mz_income = sum(isnan(mz_income))
modal_mz_income = mode(mz_income)

% mz education
mz_education = nanmean(education(is_an_mz_twin))
mz_education = nanstd(education(is_an_mz_twin))

% mz race
mz_race = sort(race(is_an_mz_twin));
[a,b,c] = unique(mz_race);
mz_race_counts = table(a,[diff(b); length(mz_race)-b(end)]/length(mz_race)*100)


n_dz = sum(sum(mz.*~isnan(topo_r(:,:,1))) > 0)
n_dz_dyads = sum(fs(:).*~isnan(mean_topo_r(:)))/2

n_dz_gt = sum(sum(dz_gt.*~isnan(topo_r(:,:,1))) > 0)
n_dz_gt_dyads = sum(dz_gt(:).*~isnan(mean_topo_r(:)))/2

is_an_dz_twin = sum(dz.*~isnan(topo_r(:,:,1))) ~= 0;

% dz age
dz_age_mean = mean(age(is_an_dz_twin))
dz_age_sd = std(age(is_an_dz_twin))

% dz sex
dz_n_female = sum(female(is_an_dz_twin))/sum(is_an_dz_twin)

% dz income
dz_income = sort(income(is_an_dz_twin));
[a,b] = unique(dz_income(~isnan(dz_income)));
dz_income_bracket_counts = [a,[diff(b); length(dz_income) - b(end)]/length(dz_income)*100]
unreported_dz_income = sum(isnan(dz_income))
modal_dz_income = mode(dz_income)

% dz education
dz_education = nanmean(education(is_an_dz_twin))
dz_education = nanstd(education(is_an_dz_twin))

% dz race
dz_race = sort(race(is_an_dz_twin));
[a,b,c] = unique(dz_race);
dz_race_counts = table(a,[diff(b); length(dz_race)-b(end)]/length(dz_race)*100)


n_fs = sum(sum(fs.*~isnan(topo_r(:,:,1))) > 0)
n_fs_dyads = sum(fs(:).*~isnan(mean_topo_r(:)))/2

is_an_fs_twin = sum(fs.*~isnan(topo_r(:,:,1))) ~= 0;

% fs age
fs_age_mean = mean(age(is_an_fs_twin))
fs_age_sd = std(age(is_an_fs_twin))

% fs sex
fs_n_female = sum(female(is_an_fs_twin))/sum(is_an_fs_twin)

% fs income
fs_income = sort(income(is_an_fs_twin));
[a,b] = unique(fs_income(~isnan(fs_income)));
fs_income_bracket_counts = [a,[diff(b); length(fs_income)-b(end)]/length(fs_income)*100]
unreported_fs_income = sum(isnan(fs_income))
modal_fs_income = mode(fs_income)

% fs education
fs_education = nanmean(education(is_an_fs_twin))
fs_education = nanstd(education(is_an_fs_twin))

% fs race
fs_race = sort(race(is_an_fs_twin));
[a,b,c] = unique(fs_race);
fs_race_counts = table(a,[diff(b); length(fs_race)-b(end)]/length(fs_race)*100)


n_hs = sum(sum(hs.*~isnan(topo_r(:,:,1))) > 0)
n_hs_dyads = sum(hs(:).*~isnan(mean_topo_r(:)))/2

is_an_hs_twin = sum(hs.*~isnan(topo_r(:,:,1))) ~= 0;

% hs age
hs_age_mean = mean(age(is_an_hs_twin))
hs_age_sd = std(age(is_an_hs_twin))

% hs sex
hs_n_female = sum(female(is_an_hs_twin))/sum(is_an_hs_twin)

% hs income
hs_income = sort(income(is_an_hs_twin));
[a,b] = unique(hs_income(~isnan(hs_income)));
hs_income_bracket_counts = [a,[diff(b); length(hs_income)-b(end)]/length(hs_income)*100]
unreported_hs_income = sum(isnan(hs_income))
modal_hs_income = mode(hs_income)

% hs education
hs_education = nanmean(education(is_an_hs_twin))
hs_education = nanstd(education(is_an_hs_twin))

% hs race
hs_race = sort(race(is_an_hs_twin));
[a,b,c] = unique(hs_race);
fs_race_counts = table(a,[diff(b); length(hs_race)-b(end)]/length(hs_race)*100)


n_unr = sum(sum(unr.*~isnan(topo_r(:,:,1))) > 0)
n_unr_dyads = sum(unr(:).*~isnan(mean_topo_r(:)))/2

is_an_unr_twin = sum(unr.*~isnan(topo_r(:,:,1))) ~= 0;

% unr age
unr_age_mean = mean(age(is_an_unr_twin))
unr_age_sd = std(age(is_an_unr_twin))

% unr sex
unr_n_female = sum(female(is_an_unr_twin))/sum(is_an_unr_twin)

% unr income
unr_income = sort(income(is_an_unr_twin));
[a,b] = unique(unr_income(~isnan(unr_income)));
unr_income_bracket_counts = [a,[diff(b); length(unr_income)-b(end)]/length(unr_income)*100]
unreported_unr_income = sum(isnan(unr_income))
modal_unr_income = mode(unr_income)

% unr education
unr_education = nanmean(education(is_an_unr_twin))
unr_education = nanstd(education(is_an_unr_twin))

% unr race
unr_race = sort(race(is_an_unr_twin));
[a,b,c] = unique(unr_race);
unr_income_bracket_counts = table(a,[diff(b); length(unr_race)-b(end)]/length(unr_race)*100)


%% get bootstrap and jackknife samples from task data
uniq_family = unique(restricted.Family_ID);
family_ind = {};
for i = 1:length(uniq_family)
    family_ind{i} = find(strcmp(uniq_family(i),restricted.Family_ID));
end
perm_inds = zeros(length(perm), length(family_ind));
for i = 1:perm
    perm_inds(i,:) = randi(length(family_ind), length(family_ind),1);
end

[task_topo_B_bs, task_topo_B_jk, task_topo_B, ...
    task_topo_clusters_bs, task_topo_clusters_jk, task_topo_clusters] = bootstrap(...
    mean_topo_r, perm, family_ind, mz, dz, fs, hs, unr, ACE, perm_inds);

disp('Mean task topography ACE model coefficients');
disp(task_topo_B)

%{
topo_B =

    0.0615
   -0.0050
   -0.0115
   -0.0204
    0.1636
%}


[task_geom_B_bs, task_geom_B_jk, task_geom_B, ...
    task_geom_clusters_bs, task_geom_clusters_jk, task_geom_clusters] = bootstrap(...
    mean_geom_r, perm, family_ind, mz, dz, fs, hs, unr, ACE, perm_inds);

disp('Mean task geometry ACE model coefficients');
disp(task_geom_B)

% mean heritability and environmental effects on geometries
% h2 = B(1)
% c2_tw = B(2)
% c2_fs = B(3)
% c2_hs = B(4)
% gc2 = B(5)

%{
geom_B =

    0.0440
    0.0071
   -0.0030
   -0.0327
    0.2988
%}


%% load exhaustive cosine similarities and goemetric similarities of RSNs
load(sprintf('rsn_topographic_similarities_%s.mat',noise),'rsn_roi_topo','rsn_good_topo');

geom_bsc = dir(fullfile(rsn_root,sprintf('bsc_all/%s_betas/cosine/*v_all.tsv',noise)));
roi_geom_rsn0 = zeros(length(geom_bsc),length(geom_bsc),518);
for i = 1:length(geom_bsc)
    csv = readmatrix(fullfile(geom_bsc(i).folder, geom_bsc(i).name),'FileType','text');
    [roi_geom_rsn0(i,(i+1):end,:), roi_geom_rsn0((i+1):end,i,:)] = deal(csv);
    roi_geom_rsn0(i,i) = 1;
end

% check for correspondence between roi_topo and roi_geom
geom_sid = arrayfun(@(x1)(str2double(strrep(x1.name,'_v_all.tsv',''))), geom_bsc);
topo_sid = restricted.Subject(rsn_good_topo);
for i = 1:length(geom_sid)
    assert(geom_sid(i) == topo_sid(i));
end

% expand roi_geom to match topo_roi (and more importantly restricted)
rsn_roi_geom = nan(size(rsn_roi_topo));
rsn_roi_geom(rsn_good_topo, rsn_good_topo,:) = roi_geom_rsn0;
clear roi_geom_rsn0

rsn_mean_topo_r = nanmean(rsn_roi_topo,3);
rsn_mean_geom_r = nanmean(rsn_roi_geom,3);

%% get bootstrap and jackknife samples from RSN data

[rsn_topo_B_bs, rsn_topo_B_jk, rsn_topo_B, ...
    rsn_topo_clusters_bs, rsn_topo_clusters_jk, rsn_topo_clusters] = bootstrap(...
    rsn_mean_topo_r, perm, family_ind, mz, dz, fs, hs, unr, ACE, perm_inds);

disp('Mean rsn topography ACE model coefficients');
disp(rsn_topo_B)

%{
rsn_topo_B =

    0.0798
   -0.0095
   -0.0157
   -0.0076
    0.1956
%}

[rsn_geom_B_bs, rsn_geom_B_jk, rsn_geom_B, ...
    rsn_geom_clusters_bs, rsn_geom_clusters_jk, rsn_geom_clusters] = bootstrap(...
    rsn_mean_geom_r, perm, family_ind, mz, dz, fs, hs, unr, ACE, perm_inds);

disp('Mean rsn geometry ACE model coefficients');
disp(rsn_geom_B)

% mean heritability and environmental effects on geometries
% h2 = B(1)
% c2_tw = B(2)
% c2_fs = B(3)
% c2_hs = B(4)
% gc2 = B(5)

%{
rsn_geom_B =

    0.0874
    0.0036
   -0.0150
    0.0136
    0.2482
%}


%% estimate mean regional task topography heritabilities

for i = 1:length(task_topo_clusters)
    [~, task_topo_clusters_CI(i,:)] = BCa(task_topo_clusters(i), task_topo_clusters_bs(i,:), task_topo_clusters_jk(i,:), 0.05);
end

% find independent subset of unrelated individuals, excluding those used
% for mz, dz, fs, hs

topo_r(any(isnan(topo_r),3)) = nan;
mean_topo_r = nanmean(topo_r,3);
[task_topo_r_mz, task_topo_r_dz, task_topo_r_fs, task_topo_r_hs, task_topo_r_unr] = get_independent_obs( ...
    mean_topo_r, mz, dz, fs, hs, unr);

%% estimate mean task geometry heritabilities

for i = 1:length(task_geom_clusters)
    [~, task_geom_clusters_CI(i,:)] = BCa(task_geom_clusters(i), task_geom_clusters_bs(i,:), task_geom_clusters_jk(i,:), 0.05);
end

% find independent subset of unrelated individuals, excluding those used
% for mz, dz, fs, hs
geom_r(any(isnan(topo_r),3)) = nan;
mean_geom_r = nanmean(geom_r,3);
[task_geom_r_mz, task_geom_r_dz, task_geom_r_fs, task_geom_r_hs, task_geom_r_unr] = get_independent_obs( ...
    mean_geom_r, mz, dz, fs, hs, unr);

%% estimate mean regional RSN topography heritabilities

for i = 1:length(rsn_topo_clusters)
    [~, rsn_topo_clusters_CI(i,:)] = BCa(rsn_topo_clusters(i), rsn_topo_clusters_bs(i,:), rsn_topo_clusters_jk(i,:), 0.05);
end

% find independent subset of unrelated individuals, excluding those used
% for mz, dz, fs, hs

rsn_roi_topo(any(isnan(topo_r),3)) = nan;
rsn_mean_topo_r = nanmean(rsn_roi_topo,3);
[rsn_topo_r_mz, rsn_topo_r_dz, rsn_topo_r_fs, rsn_topo_r_hs, rsn_topo_r_unr] = get_independent_obs( ...
    rsn_mean_topo_r, mz, dz, fs, hs, unr);

%% estimate mean RSN geometry heritabilities

for i = 1:length(rsn_geom_clusters)
    [~, rsn_geom_clusters_CI(i,:)] = BCa(rsn_geom_clusters(i), rsn_geom_clusters_bs(i,:), rsn_geom_clusters_jk(i,:), 0.05);
end

% find independent subset of unrelated individuals, excluding those used
% for mz, dz, fs, hs
rsn_roi_geom(any(isnan(rsn_roi_topo),3)) = nan;
rsn_mean_geom_r = nanmean(rsn_roi_geom,3);
[rsn_geom_r_mz, rsn_geom_r_dz, rsn_geom_r_fs, rsn_geom_r_hs, rsn_geom_r_unr] = get_independent_obs( ...
    rsn_mean_geom_r, mz, dz, fs, hs, unr);

%% estimate ACE coefficients

[task_topo_ACE, task_geom_ACE, rsn_topo_ACE, rsn_geom_ACE] = deal(cell(size(ACE,2),1));
[task_prop_topo_ACE, task_prop_geom_ACE, rsn_prop_topo_ACE, rsn_prop_geom_ACE] = deal(cell(size(ACE,2),1));
[task_prop_herit_diff, rsn_prop_herit_diff] = deal(zeros(size(ACE,2),2));
for i = 1:size(ACE,2)
    % task
    [~, task_topo_ACE{i}] = BCa(task_topo_B(i), task_topo_B_bs(i,:), task_topo_B_jk(i,:), 0.05);
    [~, task_geom_ACE{i}] = BCa(task_geom_B(i), task_geom_B_bs(i,:), task_geom_B_jk(i,:), 0.05);

    [~, task_prop_topo_ACE{i}] = BCa(task_topo_B(i)/task_topo_B(end), task_topo_B_bs(i,:)./task_topo_B_bs(end,:), task_topo_B_jk(i,:)./task_topo_B_jk(end,:), 0.05);
    [~, task_prop_geom_ACE{i}] = BCa(task_geom_B(i)/task_geom_B(end), task_geom_B_bs(i,:)./task_geom_B_bs(end,:), task_geom_B_jk(i,:)./task_geom_B_jk(end,:), 0.05);

    % difference in proportional heritabilities of topographies and
    % geometries. Note: This is only valid if bootstrap samples are
    % synchronized across topographic and geometric comparisons
    task_topo_gt_geom = task_topo_B(i)/task_topo_B(end) - task_geom_B(i)/task_geom_B(end);
    task_topo_gt_geom_jk = task_topo_B_jk(i,:)./task_topo_B_jk(end,:) - task_geom_B_jk(i,:)./task_geom_B_jk(end,:);
    task_topo_gt_geom_bs = task_topo_B_bs(i,:)./task_topo_B_bs(end,:) - task_geom_B_bs(i,:)./task_geom_B_bs(end,:);
    [~, task_prop_herit_diff(i,:)] = BCa(task_topo_gt_geom, task_topo_gt_geom_bs, task_topo_gt_geom_jk, 0.05);

    % rsn
    [~, rsn_topo_ACE{i}] = BCa(rsn_topo_B(i), rsn_topo_B_bs(i,:), rsn_topo_B_jk(i,:), 0.05);
    [~, rsn_geom_ACE{i}] = BCa(rsn_geom_B(i), rsn_geom_B_bs(i,:), rsn_geom_B_jk(i,:), 0.05);

    [~, rsn_prop_topo_ACE{i}] = BCa(rsn_topo_B(i)/rsn_topo_B(end), rsn_topo_B_bs(i,:)./rsn_topo_B_bs(end,:), rsn_topo_B_jk(i,:)./rsn_topo_B_jk(end,:), 0.05);
    [~, rsn_prop_geom_ACE{i}] = BCa(rsn_geom_B(i)/rsn_geom_B(end), rsn_geom_B_bs(i,:)./rsn_geom_B_bs(end,:), rsn_geom_B_jk(i,:)./rsn_geom_B_jk(end,:), 0.05);

    % difference in proportional heritabilities of topographies and
    % geometries. Note: This is only valid if bootstrap samples are
    % synchronized across topographic and geometric comparisons
    rsn_topo_gt_geom = rsn_topo_B(i)/rsn_topo_B(end) - rsn_geom_B(i)/rsn_geom_B(end);
    rsn_topo_gt_geom_jk = rsn_topo_B_jk(i,:)./rsn_topo_B_jk(end,:) - rsn_geom_B_jk(i,:)./rsn_geom_B_jk(end,:);
    rsn_topo_gt_geom_bs = rsn_topo_B_bs(i,:)./rsn_topo_B_bs(end,:) - rsn_geom_B_bs(i,:)./rsn_geom_B_bs(end,:);
    [~, rsn_prop_herit_diff(i,:)] = BCa(rsn_topo_gt_geom, rsn_topo_gt_geom_bs, rsn_topo_gt_geom_jk, 0.05);
end

task_topo_ACE_CI = cat(1,task_topo_ACE{:});
task_geom_ACE_CI = cat(1,task_geom_ACE{:});

task_prop_topo_ACE_CI = cat(1,task_prop_topo_ACE{:});
task_prop_geom_ACE_CI = cat(1,task_prop_geom_ACE{:});

rsn_topo_ACE_CI = cat(1,rsn_topo_ACE{:});
rsn_geom_ACE_CI = cat(1,rsn_geom_ACE{:});

rsn_prop_topo_ACE_CI = cat(1,rsn_prop_topo_ACE{:});
rsn_prop_geom_ACE_CI = cat(1,rsn_prop_geom_ACE{:});

%% Plot bargraphs

f1 = figure(98); 
lines = colormap('lines');
lines_dark = tanh(atanh(2*(lines - 0.5)) - 0.3)/2 + 0.5;
lines_darkest = tanh(atanh(2*(lines - 0.5)) - 0.8)/2 + 0.5;

clf
t0 = tiledlayout(2,2,'Padding','none','TileSpacing','compact');
ax1 = nexttile();
cla
bar(task_topo_clusters, 'FaceColor', lines(1,:), 'FaceAlpha', 0.5);
hold on;
violinplot({task_topo_r_mz, task_topo_r_dz, task_topo_r_fs, task_topo_r_hs, task_topo_r_unr}, ...
    'pointsize', 3, 'facecolor', lines(1,:), 'edgecolor', lines_dark(1,:), ...
    'vwidth', 0.66);
h = errorbar(1:5, task_topo_clusters(:),...
    task_topo_clusters(:) - task_topo_clusters_CI(:,1),task_topo_clusters(:) - task_topo_clusters_CI(:,2), ...
    'LineStyle','none','color',lines_darkest(1,:),'linewidth',2);
title({'Task Topography'},'FontWeight','normal'); 
set(gca,'FontSize',fontsize+2,'XTickLabels',[]);
ylabel({'Mean Regional Similarity',['(cos\theta', char(177), ' CI_{95})']});
grid on
box off
yl1 = ylim;

ax2 = nexttile();
cla
bar(task_geom_clusters, 'FaceColor', lines(1,:), 'FaceAlpha', 0.5);
hold on;
violinplot({task_geom_r_mz, task_geom_r_dz, task_geom_r_fs, task_geom_r_hs, task_geom_r_unr}, ...
    'pointsize', 3, 'facecolor', lines(1,:), 'edgecolor', lines_dark(1,:), ...
    'vwidth', 0.66);
h = errorbar(1:5, task_geom_clusters(:),...
    task_geom_clusters(:) - task_geom_clusters_CI(:,1),task_geom_clusters(:) - task_geom_clusters_CI(:,2), ...
    'LineStyle','none','color',lines_darkest(1,:),'linewidth',2);
title({'Task Geometry'},'FontWeight','normal'); 
set(gca,'FontSize',fontsize+2,'XTickLabels',[]);
ylabel({'Mean Regional Similarity',['(WUC', char(177), ' CI_{95})']});
grid on
box off
yl2 = ylim;

ax3 = nexttile();
cla
bar(rsn_topo_clusters, 'FaceColor', lines(2,:), 'FaceAlpha', 0.5);
hold on;
violinplot({rsn_topo_r_mz, rsn_topo_r_dz, rsn_topo_r_fs, rsn_topo_r_hs, rsn_topo_r_unr}, ...
    'pointsize', 3, 'facecolor', lines(2,:), 'edgecolor', lines_dark(2,:), ...
    'vwidth', 0.66);
h = errorbar(1:5, rsn_topo_clusters(:),...
    rsn_topo_clusters(:) - rsn_topo_clusters_CI(:,1),rsn_topo_clusters(:) - rsn_topo_clusters_CI(:,2), ...
    'LineStyle','none','color',lines_darkest(2,:),'linewidth',2);
title({'RSN Topography'},'FontWeight','normal'); 
set(gca,'XTickLabels',{'Twins (MZ)','Twins (DZ)','Siblings (Full)','Siblings (Half)','Unrelated'},'FontSize',fontsize+2,'XTickLabelRotation', 90);
ylabel({'Mean Regional Similarity',['(cos\theta', char(177), ' CI_{95})']});
grid on
box off
yl3 = ylim;

ax4 = nexttile();
cla
bar(rsn_geom_clusters, 'FaceColor', lines(2,:), 'FaceAlpha', 0.5);
hold on;
violinplot({rsn_geom_r_mz, rsn_geom_r_dz, rsn_geom_r_fs, rsn_geom_r_hs, rsn_geom_r_unr}, ...
    'pointsize', 3, 'facecolor', lines(2,:), 'edgecolor', lines_dark(2,:), ...
    'vwidth', 0.66);
h = errorbar(1:5, rsn_geom_clusters(:),...
    rsn_geom_clusters(:) - rsn_geom_clusters_CI(:,1),rsn_geom_clusters(:) - rsn_geom_clusters_CI(:,2), ...
    'LineStyle','none','color',lines_darkest(2,:),'linewidth',2);
title({'RSN Geometry'},'FontWeight','normal'); 
set(gca,'XTickLabels',{'Twins (MZ)','Twins (DZ)','Siblings (Full)','Siblings (Half)','Unrelated'},'FontSize',fontsize+2,'XTickLabelRotation', 90);
ylabel({'Mean Regional Similarity',['(WUC', char(177), ' CI_{95})']});
grid on
box off
yl4 = ylim;

sgtitle({'Family Clusters'},'FontSize',16,'FontWeight','BOLD');

pos = get(gcf,'Position');
set(gcf,'Position',[pos(1:2),450,650])


f2 = figure(99);
t0 = tiledlayout(2,2,'Padding','none','TileSpacing','compact');
ax5 = nexttile();
cla
y = [task_topo_B(:)];
h = bar(y, 'grouped','EdgeAlpha',0);
hold on;
ngroups = size(y,1);
nbars = size(y,2);
% Calculating the width for each bar group
groupwidth = min(0.8, nbars/(nbars + 1.5));
for i = 1:nbars
    x = (1:ngroups) - groupwidth/2 + (2*i-1) * groupwidth / (2*nbars);
    h = errorbar(x, y(:,i),...
        y(:,i) - task_topo_ACE_CI(:,1), task_topo_ACE_CI(:,2) - y(:,i), ...
        'LineStyle','none','color','bla', 'capsize', 0);
end
title({'Task Topography'},'FontWeight','normal'); 
set(gca,'XTickLabels',[],'FontSize',fontsize+2);
ylabel({'Marginal similarity',['(Marginal cos\theta ', char(177), ' CI_{95})']});
grid on
box off
yl5 = ylim;

ax6 = nexttile();
cla
y = [task_geom_B(:)];
bar(y, 'grouped','EdgeAlpha',0);
hold on;
ngroups = size(y,1);
nbars = size(y,2);
% Calculating the width for each bar group
groupwidth = min(0.8, nbars/(nbars + 1.5));
for i = 1:nbars
    x = (1:ngroups) - groupwidth/2 + (2*i-1) * groupwidth / (2*nbars);
    h = errorbar(x, y(:,i),...
        y(:,i) - task_geom_ACE_CI(:,1), task_geom_ACE_CI(:,2) - y(:,i), ...
        'LineStyle','none','color','bla', 'capsize', 0);
end
title({'Task Geometry'},'FontWeight','normal'); 
set(gca,'XTickLabels',[],'FontSize',fontsize+2);
ylabel({['(Marginal WUC ', char(177), ' CI_{95})']});
grid on
box off
yl6 = ylim;

ax7 = nexttile();
cla
y = [rsn_topo_B(:)];
h = bar(y, 'grouped','EdgeAlpha',0, 'FaceColor', lines(2,:));
hold on;
ngroups = size(y,1);
nbars = size(y,2);
% Calculating the width for each bar group
groupwidth = min(0.8, nbars/(nbars + 1.5));
for i = 1:nbars
    x = (1:ngroups) - groupwidth/2 + (2*i-1) * groupwidth / (2*nbars);
    h = errorbar(x, y(:,i),...
        y(:,i) - rsn_topo_ACE_CI(:,1), rsn_topo_ACE_CI(:,2) - y(:,i), ...
        'LineStyle','none','color','bla', 'capsize', 0);
end
title({'RSN Topography'},'FontWeight','normal'); 
set(gca,'XTickLabels',{'Heritability (h^2)','Env Twin',...
    'Env FS','Env HS','Unrelated'},'FontSize',14,'XTickLabelRotation', 90);
ylabel({'Marginal similarity',['(Marginal cos\theta ', char(177), ' CI_{95})']});
grid on
box off
yl7 = ylim;

ax8 = nexttile();
cla
y = [rsn_geom_B(:)];
bar(y, 'grouped','EdgeAlpha',0,'FaceColor',lines(2,:));
hold on;
ngroups = size(y,1);
nbars = size(y,2);
% Calculating the width for each bar group
groupwidth = min(0.8, nbars/(nbars + 1.5));
for i = 1:nbars
    x = (1:ngroups) - groupwidth/2 + (2*i-1) * groupwidth / (2*nbars);
    h = errorbar(x, y(:,i),...
        y(:,i) - rsn_geom_ACE_CI(:,1), rsn_geom_ACE_CI(:,2) - y(:,i), ...
        'LineStyle','none','color','bla', 'capsize', 0);
end
title({'RSN Geometry'},'FontWeight','normal'); 
set(gca,'XTickLabels',{'Heritability (h^2)','Env Twin',...
    'Env FS','Env HS','Unrelated'},'FontSize',14,'XTickLabelRotation', 90);
ylabel({['(Marginal WUC ', char(177), ' CI_{95})']});
grid on
box off
yl8 = ylim;

sgtitle({'Environmental and Genetic Effects'},'FontSize',16,'FontWeight','BOLD');

switch noise
    case 'standardized'
        set(ax1, 'YLim', [min([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8]), max([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8])]);
        set(ax2, 'YLim', [min([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8]), max([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8])]);
        set(ax3, 'YLim', [min([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8]), max([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8])]);
        set(ax4, 'YLim', [min([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8]), max([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8])]);
        
        set(ax5, 'YLim', [min([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8]), max([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8])]);
        set(ax6, 'YLim', [min([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8]), max([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8])]);
        set(ax7, 'YLim', [min([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8]), max([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8])]);
        set(ax8, 'YLim', [min([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8]), max([yl1, yl2, yl3, yl4, yl5, yl6, yl7, yl8])]);
    case 'whitened'
        set(ax1, 'YLim', [min([yl1, yl3, yl5, yl7]), max([yl1, yl3, yl5, yl7])]);
        set(ax2, 'YLim', [min([yl2, yl4, yl6, yl8]), max([yl2, yl4, yl6, yl8])]);
        set(ax3, 'YLim', [min([yl1, yl3, yl5, yl7]), max([yl1, yl3, yl5, yl7])]);
        set(ax4, 'YLim', [min([yl2, yl4, yl6, yl8]), max([yl2, yl4, yl6, yl8])]);
        
        set(ax5, 'YLim', [min([yl1, yl3, yl5, yl7]), max([yl1, yl3, yl5, yl7])]);
        set(ax6, 'YLim', [min([yl2, yl4, yl6, yl8]), max([yl2, yl4, yl6, yl8])]);
        set(ax7, 'YLim', [min([yl1, yl3, yl5, yl7]), max([yl1, yl3, yl5, yl7])]);
        set(ax8, 'YLim', [min([yl2, yl4, yl6, yl8]), max([yl2, yl4, yl6, yl8])]);
end

pos = get(gcf,'Position');
set(gcf,'Position',[pos(1:2),450,650])

export_fig(f1,sprintf('panels_%s/family_clusters.png',noise),'-transparent','-r300');
export_fig(f2,sprintf('panels_%s/ACE_absolute.png',noise),'-transparent','-r300');

%% Plot relative heritabilities and contrasts
figure(100);
t0 = tiledlayout(2,11,'Padding','none','TileSpacing','compact');

ax1 = nexttile();
ax1.Layout.TileSpan = [1,6];
cla
y = [task_topo_B(1)/task_topo_B(end); task_geom_B(1)/task_geom_B(end)];
CI = [task_prop_topo_ACE_CI(1,:); task_prop_geom_ACE_CI(1,:)];
bar(y, 'grouped','EdgeAlpha',0,'FaceColor',lines_darkest(1,:));
hold on;
ngroups = size(y,1);
nbars = size(y,2);
% Calculating the width for each bar group
groupwidth = min(0.8, nbars/(nbars + 1.5));
for i = 1:nbars
    x = (1:ngroups) - groupwidth/2 + (2*i-1) * groupwidth / (2*nbars);
    h = errorbar(x, y(:,i),...
        y(:,i) - CI(:,1), CI(:,2) - y(:,i), ...
        'LineStyle','none','color',lines(1,:), 'capsize', 0);
end
title({'Task'},'FontWeight','normal'); 
set(gca,'XTickLabels',[],'FontSize',14,'XTickLabelRotation', 90);
ylabel({'Relative Heritability','(h^2/Unr)'})
grid on
box off
yl = ylim;
ylim([yl(1),yl(2)*1.2])

ax2 = nexttile();
ax2.Layout.TileSpan = [1,5];
cla
y = [task_topo_B(i)/task_topo_B(end) - task_geom_B(i)/task_geom_B(end)];
CI = [task_prop_herit_diff(1,:)];
bar(y, 'grouped','EdgeAlpha',1,'EdgeColor',lines(1,:),'FaceAlpha',0);
hold on;
ngroups = size(y,1);
nbars = size(y,2);
% Calculating the width for each bar group
groupwidth = min(0.8, nbars/(nbars + 1.5));
for i = 1:nbars
    x = (1:ngroups) - groupwidth/2 + (2*i-1) * groupwidth / (2*nbars);
    h = errorbar(x, y(:,i),...
        y(:,i) - CI(:,1), CI(:,2) - y(:,i), ...
        'LineStyle','none','color','bla', 'capsize', 0);
end
title({'Task'},'FontWeight','normal'); 
set(gca,'XTickLabels',[],'FontSize',14,'XTickLabelRotation', 90);
ylabel({'\Delta Relative Heritability','(\Deltah^2/Unr)'})
grid on
box off

yl = ylim;
ylim([yl(1),yl(2)*1.2])

ax3 = nexttile();
ax3.Layout.TileSpan = [1,6];
cla
y = [rsn_topo_B(1)/rsn_topo_B(end); rsn_geom_B(1)/rsn_geom_B(end)];
CI = [rsn_prop_topo_ACE_CI(1,:); rsn_prop_geom_ACE_CI(1,:)];
bar(y, 'grouped','EdgeAlpha',0,'FaceColor',lines_darkest(2,:));
hold on;
ngroups = size(y,1);
nbars = size(y,2);
% Calculating the width for each bar group
groupwidth = min(0.8, nbars/(nbars + 1.5));
for i = 1:nbars
    x = (1:ngroups) - groupwidth/2 + (2*i-1) * groupwidth / (2*nbars);
    h = errorbar(x, y(:,i),...
        y(:,i) - CI([1,end],1), CI([1,end],2) - y(:,i), ...
        'LineStyle','none','color',lines(2,:), 'capsize', 0);
end
title({'RSN'},'FontWeight','normal'); 
set(gca,'XTickLabels',{'Topography','Geometry'},'FontSize',14,'XTickLabelRotation', 90);
ylabel({'Relative Heritability','(h^2/Unr)'})
grid on
box off
yl = ylim;
ylim([yl(1),yl(2)*1.2])

ax4 = nexttile();
ax4.Layout.TileSpan = [1,5];
cla
y = [rsn_topo_B(i)/rsn_topo_B(end) - rsn_geom_B(i)/rsn_geom_B(end)];
CI = [rsn_prop_herit_diff(1,:)];
bar(y, 'grouped','EdgeAlpha',1,'EdgeColor',lines(2,:),'FaceAlpha',0);
hold on;
ngroups = size(y,1);
nbars = size(y,2);
% Calculating the width for each bar group
groupwidth = min(0.8, nbars/(nbars + 1.5));
for i = 1:nbars
    x = (1:ngroups) - groupwidth/2 + (2*i-1) * groupwidth / (2*nbars);
    h = errorbar(x, y(:,i),...
        y(:,i) - CI(:,1), CI(:,2) - y(:,i), ...
        'LineStyle','none','color','bla', 'capsize', 0);
end
title({'RSN'},'FontWeight','normal'); 
set(gca,'XTickLabels','Topo-Geom','FontSize',14,'XTickLabelRotation', 90);
ylabel({'\Delta Relative Heritability','(\Deltah^2/Unr)'})
grid on
box off
yl = ylim;
ylim([yl(1),yl(2)*1.2])

sgtitle({'Contrasts of','Relative Effects'},'FontWeight','bold','fontsize',fontsize+4)

pos = get(gcf,'Position');
set(gcf,'Position',[pos(1:2),305,650])

export_fig(gcf,sprintf('panels_%s/ACE_proportional.png',noise),'-transparent','-r300');

%% Print tables

disp('Task Topo')
for i = 1:5
    fprintf('%0.3f ± [%0.3f, %0.3f]\n', task_topo_B(i), task_topo_ACE_CI(i,1), task_topo_ACE_CI(i,2));
end

disp('Task Geom')
for i = 1:5
    fprintf('%0.3f ± [%0.3f, %0.3f]\n', task_geom_B(i), task_geom_ACE_CI(i,1), task_geom_ACE_CI(i,2));
end


disp('RSN Topo')
for i = 1:5
    fprintf('%0.3f ± [%0.3f, %0.3f]\n', rsn_topo_B(i), rsn_topo_ACE_CI(i,1), rsn_topo_ACE_CI(i,2));
end

disp('RSN Geom')
for i = 1:5
    fprintf('%0.3f ± [%0.3f, %0.3f]\n', rsn_geom_B(i), rsn_geom_ACE_CI(i,1), rsn_geom_ACE_CI(i,2));
end

%% Nonparametric tests of heritability
tril_ind = tril(true(size(dz)),-1);

disp('Task Topography')
x = mean_topo_r(mz & tril_ind);
y = mean_topo_r(dz & tril_ind);
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P,H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

disp('Task Geometry')
x = mean_geom_r(mz & tril_ind);
y = mean_geom_r(dz & tril_ind);
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P,H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

disp('RSN Topography')
x = rsn_mean_topo_r(mz & tril_ind);
y = rsn_mean_topo_r(dz & tril_ind);
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P,H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

disp('RSN Geometry')
x = rsn_mean_geom_r(mz & tril_ind);
y = rsn_mean_geom_r(dz & tril_ind);
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P,H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

%% Nonparmaetric interaction tests of mz vs. dz x geometry vs. topography

mz_topo = mean_topo_r(mz & tril_ind);
dz_topo = mean_topo_r(dz & tril_ind);
mz_geom = mean_geom_r(mz & tril_ind);
dz_geom = mean_geom_r(dz & tril_ind);

nx = length(mz_topo);
ny = length(dz_topo);
grp = [1*ones(nx,1); -1*ones(ny,1)];

topo = [mz_topo; dz_topo];
geom = [mz_geom; dz_geom];

has_data = ~isnan(topo) & ~isnan(geom);

topo = rankdata(topo(has_data));
geom = rankdata(geom(has_data));
grp = grp(has_data);

dmz = topo(grp > 0) - geom(grp > 0);
ddz = topo(grp < 0) - geom(grp < 0);

disp('MZ vs. DZ x Geometry vs. Topography (task):')
[P,H,STATS] = ranksum(dmz,ddz,'tail','right')
U = STATS.ranksum - length(dmz)*(length(dmz) + 1)/2
AUC = U/(length(dmz)*length(ddz))



mz_topo = rsn_mean_topo_r(mz & tril_ind);
dz_topo = rsn_mean_topo_r(dz & tril_ind);
mz_geom = rsn_mean_geom_r(mz & tril_ind);
dz_geom = rsn_mean_geom_r(dz & tril_ind);

nx = length(mz_topo);
ny = length(dz_topo);
grp = [1*ones(nx,1); -1*ones(ny,1)];

topo = [mz_topo; dz_topo];
geom = [mz_geom; dz_geom];

has_data = ~isnan(topo) & ~isnan(geom);

topo = rankdata(topo(has_data));
geom = rankdata(geom(has_data));
grp = grp(has_data);

dmz = topo(grp > 0) - geom(grp > 0);
ddz = topo(grp < 0) - geom(grp < 0);

disp('MZ vs. DZ x Geometry vs. Topography (RSN):')
[P,H,STATS] = ranksum(dmz,ddz,'tail','right')
U = STATS.ranksum - length(dmz)*(length(dmz) + 1)/2
AUC = U/(length(dmz)*length(ddz))

%% Nonparametric tests of dz vs. fs environment
P = zeros(4,1);

disp('Task Topography')
x = mean_topo_r(dz & tril_ind);
y = mean_topo_r(fs & tril_ind);
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P(1),H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

disp('Task Geometry')
x = mean_geom_r(dz & tril_ind);
y = mean_geom_r(fs & tril_ind);
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P(2),H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

disp('RSN Topography')
x = rsn_mean_topo_r(dz & tril_ind);
y = rsn_mean_topo_r(fs & tril_ind);
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P(3),H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

disp('RSN Geometry')
x = rsn_mean_geom_r(dz & tril_ind);
y = rsn_mean_geom_r(fs & tril_ind);
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P(4),H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

%% Nonparmaetric interaction tests of dz vs. fs x geometry vs. topography

dz_topo = mean_topo_r(dz & tril_ind);
fs_topo = mean_topo_r(fs & tril_ind);
dz_geom = mean_geom_r(dz & tril_ind);
fs_geom = mean_geom_r(fs & tril_ind);

nx = length(dz_topo);
ny = length(fs_topo);
grp = [1*ones(nx,1); -1*ones(ny,1)];

topo = [dz_topo; fs_topo];
geom = [dz_geom; fs_geom];

has_data = ~isnan(topo) & ~isnan(geom);

topo = rankdata(topo(has_data));
geom = rankdata(geom(has_data));
grp = grp(has_data);

ddz = geom(grp > 0) - topo(grp > 0);
dfs = geom(grp < 0) - topo(grp < 0);

disp('DZ vs. FS x Geometry vs. Topography (Task):')
[P,H,STATS] = ranksum(ddz,dfs,'tail','right')
U = STATS.ranksum - length(ddz)*(length(ddz) + 1)/2
AUC = U/(length(ddz)*length(dfs))


dz_topo = rsn_mean_topo_r(dz & tril_ind);
fs_topo = rsn_mean_topo_r(fs & tril_ind);
dz_geom = rsn_mean_geom_r(dz & tril_ind);
fs_geom = rsn_mean_geom_r(fs & tril_ind);

nx = length(dz_topo);
ny = length(fs_topo);
grp = [1*ones(nx,1); -1*ones(ny,1)];

topo = [dz_topo; fs_topo];
geom = [dz_geom; fs_geom];

has_data = ~isnan(topo) & ~isnan(geom);

topo = rankdata(topo(has_data));
geom = rankdata(geom(has_data));
grp = grp(has_data);

ddz = geom(grp > 0) - topo(grp > 0);
dfs = geom(grp < 0) - topo(grp < 0);

disp('DZ vs. FS x Geometry vs. Topography (RSN):')
[P,H,STATS] = ranksum(ddz,dfs,'tail','right')
U = STATS.ranksum - length(ddz)*(length(ddz) + 1)/2
AUC = U/(length(ddz)*length(dfs))

