% Before running this script make sure that
% task_topographic_similarities.mat and rsn_topographic_similarities.mat
% are available in the current working directory. These can be generated by
% - prepare_task_topographic_similarities.m
% - prepare_rsn_topographic_similarities.m

close all; clear all;

config = jsondecode(fileread('../../config.json'));

addpath(config.matlab_libraries.spm12);
addpath(genpath(config.matlab_libraries.cifti_matlab));
addpath(genpath(fullfile(config.matlab_libraries.canlabCore, 'CanlabCore')));

addpath('../../matlab_libraries');
addpath('../../resources/neuromaps');

fontsize=config.matlab_disp_scheme.fontsize;

f = figure;
cm = colormap(f,'hot');
close(f)

dc_color = config.matlab_disp_scheme.color_main;
dc_color_light = config.matlab_disp_scheme.color_light;

unrestricted = readtable(config.hcp_participant_data.unrestricted);
restricted = readtable(config.hcp_participant_data.restricted);
n_subj = height(restricted);

perm = 5000;

data_root = '../../derivatives/hcp_glm_msmall_grayord_spm/';
rsn_root = '../../derivatives/restingstate/hcp25/';

noise='whitened';

%% import atlas in cifti space and get region names
atlas_cii = cifti_read(config.canlab2024.path);
atlas_labels = atlas_cii.diminfo{2}.maps.table(2:end); % drop first label, it corresponds to 0-valued vertices, i.e. the medial wall
roi_labels = {atlas_labels.name}; 

atlas_cii = get_cifti_data(config.canlab2024.path);
n_roi = length(unique([atlas_cii.cortex_left, atlas_cii.cortex_right, atlas_cii.volumes])) - 1;

%% get family clusters

% get all within family mz relationsips
[female, age, income, education] = deal(nan(height(restricted),1));
race = cell(height(restricted),1);
[non_gt_twin, hs, fs, dz, mz, mz_gt, dz_gt, mz_sr, dz_sr] = deal(false(height(restricted)));
for i = 1:height(restricted)
    this_sid = restricted.Subject(i); 
    family_ind = restricted.Father_ID == restricted.Father_ID(i) & restricted.Mother_ID == restricted.Mother_ID(i);
    
    age(i) = restricted.Age_in_Yrs(i);
    female(i) = ~strcmp(unrestricted.Gender{unrestricted.Subject == this_sid}, 'M');
    income(i) = restricted.SSAGA_Income(i);
    education(i) = restricted.SSAGA_Educ(i);
    if strcmp(restricted.Ethnicity(i),'Hispanic/Latino')
        race(i) = {'Hispanic/Latino'};
    else
        race(i) = restricted.Race(i);
    end
    
    switch restricted.ZygositySR{i}
        case 'NotTwin'
            [fs(i, family_ind), fs(family_ind, i)] = deal(true);
        case {'MZ', 'NotMZ'}
            switch restricted.ZygosityGT{i}
                case 'MZ'
                    twin_ind = find((strcmp(restricted.ZygosityGT, 'MZ') | strcmp(restricted.ZygositySR, 'MZ')) ...
                        & family_ind);
                    %twin_ind = find(strcmp(restricted.ZygosityGT, 'MZ') & family_ind);
                    [mz(i, twin_ind), mz(twin_ind,i), mz_gt(i,twin_ind), mz_gt(twin_ind,i)] = deal(true);

                    nontwin_sib = find(~strcmp(restricted.ZygosityGT, 'MZ') & ~strcmp(restricted.ZygositySR, 'MZ') ...
                        & family_ind);
                    [fs(i, nontwin_sib), fs(nontwin_sib, i)] = deal(true);
                case 'DZ'
                    twin_ind = find((strcmp(restricted.ZygosityGT, 'DZ') | strcmp(restricted.ZygositySR, 'NotMZ')) & ...
                        family_ind);
                    %twin_ind = find(strcmp(restricted.ZygosityGT, 'DZ') & family_ind);
                    [dz(i, twin_ind), dz(twin_ind,i), dz_gt(i,twin_ind), dz_gt(twin_ind,i)] = deal(true);

                    nontwin_sib = find(~strcmp(restricted.ZygosityGT, 'DZ') & ~strcmp(restricted.ZygositySR, 'NotMZ') ...
                        & family_ind);
                    [fs(i, nontwin_sib), fs(nontwin_sib, i)] = deal(true);
                otherwise
                    switch restricted.ZygositySR{i}
                        case 'MZ'
                            twin_ind = find(strcmp(restricted.ZygositySR, 'MZ') & family_ind);
                            %[non_gt_twin(i, twin_ind), non_gt_twin(twin_ind,i)] = deal(true);
                            [mz(i, twin_ind), mz(twin_ind,i), mz_sr(i,twin_ind), mz_sr(twin_ind,i)] = deal(true);
            
                            nontwin_sib = find(~strcmp(restricted.ZygositySR, 'MZ') & family_ind);
                            [fs(i, nontwin_sib), fs(nontwin_sib, i)] = deal(true);
                        case 'NotMZ'
                            twin_ind = find(strcmp(restricted.ZygositySR, 'NotMZ') & family_ind);
                            %[non_gt_twin(i, twin_ind), non_gt_twin(twin_ind,i)] = deal(true);
                            [dz(i, twin_ind), dz(twin_ind,i), dz_sr(i,twin_ind), dz_sr(twin_ind,i)] = deal(true);
            
                            nontwin_sib = find(~strcmp(restricted.ZygositySR, 'NotMZ') & family_ind);
                            [fs(i, nontwin_sib), fs(nontwin_sib, i)] = deal(true);
                    end
                    fprintf('Subject %d is missing genotypically identified data. GR entry: %s\n', restricted.Subject(i), restricted.ZygosityGT{i});
            end
        otherwise
            fprintf('Subject %d has unexpected self reported zygosity: %s\n', restricted.Subject(i), restricted.ZygositySR{i});
    end

    half_sib = find(xor(restricted.Mother_ID == restricted.Mother_ID(i), restricted.Father_ID == restricted.Father_ID(i)));
    [hs(i, half_sib), hs(half_sib, i)] = deal(true);
end

hs = hs & ~eye(height(restricted));
fs = fs & ~eye(height(restricted));
dz = dz & ~eye(height(restricted)); 
mz = mz & ~eye(height(restricted));

unr = ~hs & ~fs & ~mz & ~dz & ~non_gt_twin & ~eye(height(restricted));

mz_gt = mz_gt & ~eye(height(restricted));
mz_sr = mz_sr & ~eye(height(restricted));
dz_gt = dz_gt & ~eye(height(restricted));
dz_sr = dz_sr & ~eye(height(restricted));


%% load exhaustive cosine similarities and goemetric similarities of tasks
load(sprintf('task_topographic_similarities_%s.mat', noise),'roi_topo','good_topo');

geom_bsc = dir(fullfile(data_root,sprintf('bsc_all/%s_betas/cosine/*v_all.tsv',noise)));
roi_geom0 = zeros(length(geom_bsc),length(geom_bsc),518);
for i = 1:length(geom_bsc)
    csv = readmatrix(fullfile(geom_bsc(i).folder, geom_bsc(i).name),'FileType','text');
    [roi_geom0(i,(i+1):end,:), roi_geom0((i+1):end,i,:)] = deal(csv);
    roi_geom0(i,i) = 1;
end

% check for correspondence between roi_topo and roi_geom
geom_sid = arrayfun(@(x1)(str2double(strrep(x1.name,'_v_all.tsv',''))), geom_bsc);
topo_sid = unrestricted.Subject(good_topo);
for i = 1:length(geom_sid)
    assert(geom_sid(i) == topo_sid(i));
end

% expand roi_geom to match topo_roi (and more importantly restricted)
roi_geom = nan(size(roi_topo));
roi_geom(good_topo, good_topo,:) = roi_geom0;
clear roi_geom0

%% trival renaming for legacy code reuse
topo_r = roi_topo;
geom_r = roi_geom;

mean_topo_r = nanmean(topo_r,3);
mean_geom_r = nanmean(geom_r,3);

%% print subject counts
% this information is used to population demographic tables

n_mz = sum(sum(mz.*~isnan(topo_r(:,:,1))) > 0)
n_mz_dyads = sum(mz(:).*~isnan(mean_topo_r(:)))/2

n_mz_gt = sum(sum(mz_gt.*~isnan(topo_r(:,:,1))) > 0)
n_mz_gt_dyads = sum(mz_gt(:).*~isnan(mean_topo_r(:)))/2

is_an_mz_twin = sum(mz.*~isnan(topo_r(:,:,1))) ~= 0;

% mz age
mz_age_mean = mean(age(is_an_mz_twin))
mz_age_sd = std(age(is_an_mz_twin))

% mz sex
mz_n_female = sum(female(is_an_mz_twin))/sum(is_an_mz_twin)

% mz income
mz_income = sort(income(is_an_mz_twin));
[a,b] = unique(mz_income(~isnan(mz_income)));
mz_income_bracket_counts = [a,[diff(b); length(mz_income)-b(end)]/length(mz_income)*100]
unreported_mz_income = sum(isnan(mz_income))
modal_mz_income = mode(mz_income)

% mz education
mz_education = nanmean(education(is_an_mz_twin))
mz_education = nanstd(education(is_an_mz_twin))

% mz race
mz_race = sort(race(is_an_mz_twin));
[a,b,c] = unique(mz_race);
mz_race_counts = table(a,[diff(b); length(mz_race)-b(end)]/length(mz_race)*100)


n_dz = sum(sum(mz.*~isnan(topo_r(:,:,1))) > 0)
n_dz_dyads = sum(fs(:).*~isnan(mean_topo_r(:)))/2

n_dz_gt = sum(sum(dz_gt.*~isnan(topo_r(:,:,1))) > 0)
n_dz_gt_dyads = sum(dz_gt(:).*~isnan(mean_topo_r(:)))/2

is_an_dz_twin = sum(dz.*~isnan(topo_r(:,:,1))) ~= 0;

% dz age
dz_age_mean = mean(age(is_an_dz_twin))
dz_age_sd = std(age(is_an_dz_twin))

% dz sex
dz_n_female = sum(female(is_an_dz_twin))/sum(is_an_dz_twin)

% dz income
dz_income = sort(income(is_an_dz_twin));
[a,b] = unique(dz_income(~isnan(dz_income)));
dz_income_bracket_counts = [a,[diff(b); length(dz_income) - b(end)]/length(dz_income)*100]
unreported_dz_income = sum(isnan(dz_income))
modal_dz_income = mode(dz_income)

% dz education
dz_education = nanmean(education(is_an_dz_twin))
dz_education = nanstd(education(is_an_dz_twin))

% dz race
dz_race = sort(race(is_an_dz_twin));
[a,b,c] = unique(dz_race);
dz_race_counts = table(a,[diff(b); length(dz_race)-b(end)]/length(dz_race)*100)


n_fs = sum(sum(fs.*~isnan(topo_r(:,:,1))) > 0)
n_fs_dyads = sum(fs(:).*~isnan(mean_topo_r(:)))/2

is_an_fs_twin = sum(fs.*~isnan(topo_r(:,:,1))) ~= 0;

% fs age
fs_age_mean = mean(age(is_an_fs_twin))
fs_age_sd = std(age(is_an_fs_twin))

% fs sex
fs_n_female = sum(female(is_an_fs_twin))/sum(is_an_fs_twin)

% fs income
fs_income = sort(income(is_an_fs_twin));
[a,b] = unique(fs_income(~isnan(fs_income)));
fs_income_bracket_counts = [a,[diff(b); length(fs_income)-b(end)]/length(fs_income)*100]
unreported_fs_income = sum(isnan(fs_income))
modal_fs_income = mode(fs_income)

% fs education
fs_education = nanmean(education(is_an_fs_twin))
fs_education = nanstd(education(is_an_fs_twin))

% fs race
fs_race = sort(race(is_an_fs_twin));
[a,b,c] = unique(fs_race);
fs_race_counts = table(a,[diff(b); length(fs_race)-b(end)]/length(fs_race)*100)


n_hs = sum(sum(hs.*~isnan(topo_r(:,:,1))) > 0)
n_hs_dyads = sum(hs(:).*~isnan(mean_topo_r(:)))/2

is_an_hs_twin = sum(hs.*~isnan(topo_r(:,:,1))) ~= 0;

% hs age
hs_age_mean = mean(age(is_an_hs_twin))
hs_age_sd = std(age(is_an_hs_twin))

% hs sex
hs_n_female = sum(female(is_an_hs_twin))/sum(is_an_hs_twin)

% hs income
hs_income = sort(income(is_an_hs_twin));
[a,b] = unique(hs_income(~isnan(hs_income)));
hs_income_bracket_counts = [a,[diff(b); length(hs_income)-b(end)]/length(hs_income)*100]
unreported_hs_income = sum(isnan(hs_income))
modal_hs_income = mode(hs_income)

% hs education
hs_education = nanmean(education(is_an_hs_twin))
hs_education = nanstd(education(is_an_hs_twin))

% hs race
hs_race = sort(race(is_an_hs_twin));
[a,b,c] = unique(hs_race);
fs_race_counts = table(a,[diff(b); length(hs_race)-b(end)]/length(hs_race)*100)


n_unr = sum(sum(unr.*~isnan(topo_r(:,:,1))) > 0)
n_unr_dyads = sum(unr(:).*~isnan(mean_topo_r(:)))/2

is_an_unr_twin = sum(unr.*~isnan(topo_r(:,:,1))) ~= 0;

% unr age
unr_age_mean = mean(age(is_an_unr_twin))
unr_age_sd = std(age(is_an_unr_twin))

% unr sex
unr_n_female = sum(female(is_an_unr_twin))/sum(is_an_unr_twin)

% unr income
unr_income = sort(income(is_an_unr_twin));
[a,b] = unique(unr_income(~isnan(unr_income)));
unr_income_bracket_counts = [a,[diff(b); length(unr_income)-b(end)]/length(unr_income)*100]
unreported_unr_income = sum(isnan(unr_income))
modal_unr_income = mode(unr_income)

% unr education
unr_education = nanmean(education(is_an_unr_twin))
unr_education = nanstd(education(is_an_unr_twin))

% unr race
unr_race = sort(race(is_an_unr_twin));
[a,b,c] = unique(unr_race);
unr_income_bracket_counts = table(a,[diff(b); length(unr_race)-b(end)]/length(unr_race)*100)


%% get bootstrap and jackknife samples from task data

uniq_family = unique(restricted.Family_ID);
family_ind = {};
for i = 1:length(uniq_family)
    family_ind{i} = find(strcmp(uniq_family(i),restricted.Family_ID));
end
perm_inds = zeros(length(perm), length(family_ind));
for i = 1:perm
    perm_inds(i,:) = randi(length(family_ind), length(family_ind),1);
end

[task_topo_clusters_bs, task_topo_clusters_jk, task_topo_clusters] = bootstrap5(...
    mean_topo_r, perm, family_ind, mz, dz, fs, hs, unr, perm_inds);

[task_geom_clusters_bs, task_geom_clusters_jk, task_geom_clusters] = bootstrap5(...
    mean_geom_r, perm, family_ind, mz, dz, fs, hs, unr, perm_inds);

%% load exhaustive cosine similarities and goemetric similarities of RSNs
load(sprintf('rsn_topographic_similarities_%s.mat',noise),'rsn_roi_topo','rsn_good_topo');

geom_bsc = dir(fullfile(rsn_root,sprintf('bsc_all/%s_betas/cosine/*v_all.tsv',noise)));
roi_geom_rsn0 = zeros(length(geom_bsc),length(geom_bsc),518);
for i = 1:length(geom_bsc)
    csv = readmatrix(fullfile(geom_bsc(i).folder, geom_bsc(i).name),'FileType','text');
    [roi_geom_rsn0(i,(i+1):end,:), roi_geom_rsn0((i+1):end,i,:)] = deal(csv);
    roi_geom_rsn0(i,i) = 1;
end

% check for correspondence between roi_topo and roi_geom
geom_sid = arrayfun(@(x1)(str2double(strrep(x1.name,'_v_all.tsv',''))), geom_bsc);
topo_sid = restricted.Subject(rsn_good_topo);
for i = 1:length(geom_sid)
    assert(geom_sid(i) == topo_sid(i));
end

% expand roi_geom to match topo_roi (and more importantly restricted)
rsn_roi_geom = nan(size(rsn_roi_topo));
rsn_roi_geom(rsn_good_topo, rsn_good_topo,:) = roi_geom_rsn0;
clear roi_geom_rsn0

rsn_mean_topo_r = nanmean(rsn_roi_topo,3);
rsn_mean_geom_r = nanmean(rsn_roi_geom,3);

%% get bootstrap and jackknife samples from RSN data

[rsn_topo_clusters_bs, rsn_topo_clusters_jk, rsn_topo_clusters] = bootstrap5(...
    rsn_mean_topo_r, perm, family_ind, mz, dz, fs, hs, unr, perm_inds);

[rsn_geom_clusters_bs, rsn_geom_clusters_jk, rsn_geom_clusters] = bootstrap5(...
    rsn_mean_geom_r, perm, family_ind, mz, dz, fs, hs, unr, perm_inds);

%% estimate mean regional task topography heritabilities

for i = 1:length(task_topo_clusters)
    [~, task_topo_clusters_CI(i,:)] = BCa(task_topo_clusters(i), task_topo_clusters_bs(i,:), task_topo_clusters_jk(i,:), 0.05);
end

% find independent subset of unrelated individuals, excluding those used
% for mz, dz, fs, hs

topo_r(any(isnan(topo_r),3)) = nan;
mean_topo_r = nanmean(topo_r,3);
[task_topo_r_mz, task_topo_r_dz, task_topo_r_fs, task_topo_r_hs, task_topo_r_unr, task_topo_r_fs_not_dz] = get_independent_obs( ...
    mean_topo_r, mz, dz, fs, hs, unr);

%% estimate mean task geometry heritabilities

for i = 1:length(task_geom_clusters)
    [~, task_geom_clusters_CI(i,:)] = BCa(task_geom_clusters(i), task_geom_clusters_bs(i,:), task_geom_clusters_jk(i,:), 0.05);
end

% find independent subset of unrelated individuals, excluding those used
% for mz, dz, fs, hs
geom_r(any(isnan(topo_r),3)) = nan;
mean_geom_r = nanmean(geom_r,3);
[task_geom_r_mz, task_geom_r_dz, task_geom_r_fs, task_geom_r_hs, task_geom_r_unr, task_geom_r_fs_not_dz] = get_independent_obs( ...
    mean_geom_r, mz, dz, fs, hs, unr);

%% estimate mean regional RSN topography heritabilities

for i = 1:length(rsn_topo_clusters)
    [~, rsn_topo_clusters_CI(i,:)] = BCa(rsn_topo_clusters(i), rsn_topo_clusters_bs(i,:), rsn_topo_clusters_jk(i,:), 0.05);
end

% find independent subset of unrelated individuals, excluding those used
% for mz, dz, fs, hs

rsn_roi_topo(any(isnan(topo_r),3)) = nan;
rsn_mean_topo_r = nanmean(rsn_roi_topo,3);
[rsn_topo_r_mz, rsn_topo_r_dz, rsn_topo_r_fs, rsn_topo_r_hs, rsn_topo_r_unr, rsn_topo_r_fs_not_dz] = get_independent_obs( ...
    rsn_mean_topo_r, mz, dz, fs, hs, unr);

%% estimate mean RSN geometry heritabilities

for i = 1:length(rsn_geom_clusters)
    [~, rsn_geom_clusters_CI(i,:)] = BCa(rsn_geom_clusters(i), rsn_geom_clusters_bs(i,:), rsn_geom_clusters_jk(i,:), 0.05);
end

% find independent subset of unrelated individuals, excluding those used
% for mz, dz, fs, hs
rsn_roi_geom(any(isnan(rsn_roi_topo),3)) = nan;
rsn_mean_geom_r = nanmean(rsn_roi_geom,3);
[rsn_geom_r_mz, rsn_geom_r_dz, rsn_geom_r_fs, rsn_geom_r_hs, rsn_geom_r_unr, rsn_geom_r_fs_not_dz] = get_independent_obs( ...
    rsn_mean_geom_r, mz, dz, fs, hs, unr);

%% Import test-retest reliability data
sid = readtable('../../resources/paired_retest_iid_sid.csv', 'ReadVariableNames',false);
sid = table([sid.Var1; sid.Var2]);

balanced_mean_op = [1/7*repmat(1/2,1,10), 1/7*repmat(1/5,1,5), 1/7*repmat(1/8,1,8)];

task_labels = [1,1,2,2,3,3,4,4,5,5,6,6,6,6,6,7,7,7,7,7,7,7,7];

task_wuc_retest = zeros(height(sid), n_roi);
for s = 1:height(sid)
    try
        task_wuc_retest(s,:) = diag(readmatrix(sprintf('../../derivatives/retest/hcp_glm_msmall_grayord_spm/bsc_retest/%s_betas/cosine/%d_v_%d_wuc.tsv',noise,sid.Var1(s),sid.Var1(s)),'FileType','text'));
    catch
        warning('Could not import pair %d', s);
    end
end
for s = 1:height(sid)
    % Some distance matrices are so noise dominated that their test-retest
    % reliability does not produce a valid RDM whitening matrix. We set
    % those to nans here. If we consider the residual non-imaginary
    % subjects for these regions we'll have biased estimates, but nans make
    % these easy to keep track of so we can mask them out later
    nan_regions = imag(task_wuc_retest(s,:)) ~= 0;
    task_wuc_retest(s, nan_regions) = nan;
end

task_cosim_retest = zeros(height(sid), n_roi);
for s = 1:height(sid)
    try
        task_cosim_retest(s,:) = balanced_mean_op*dlmread(sprintf('../../derivatives/retest/hcp_glm_msmall_grayord_spm/bsc_retest/%s_betas/cosine/%d_v_%d_cosim.tsv', noise, sid.Var1(s), sid.Var1(s)), '\t');
    catch
        warning('Could not import pair %d', s);
    end
end

has_data = any(task_cosim_retest,2) & any(~isnan(task_wuc_retest),2);

task_cosim_retest = task_cosim_retest(has_data,:);
task_wuc_retest = task_wuc_retest(has_data,:);

rsn_wuc_retest = zeros(height(sid), n_roi);
for s = 1:height(sid)
    try
        rsn_wuc_retest(s,:) = readmatrix(sprintf('../../derivatives/retest/restingstate/hcp25/bsc_retest/%s_betas/cosine/%d_v_%d_wuc.tsv',noise,sid.Var1(s),sid.Var1(s)),'FileType','text');
    catch
        warning('Could not import pair %d', s);
    end
end
for s = 1:height(sid)
    % Some distance matrices are so noise dominated that their test-retest
    % reliability does not produce a valid RDM whitening matrix. We set
    % those to nans here. If we consider the residual non-imaginary
    % subjects for these regions we'll have biased estimates, but nans make
    % these easy to keep track of so we can mask them out later
    nan_regions = imag(rsn_wuc_retest(s,:)) ~= 0;
    rsn_wuc_retest(s, nan_regions) = nan;
end

rsn_cosim_retest = zeros(height(sid), n_roi);
for s = 1:height(sid)
    try
        rsn_cosim_retest(s,:) = mean(dlmread(sprintf('../../derivatives/retest/restingstate/hcp25/bsc_retest/%s_betas/cosine/%d_v_%d_cosim.tsv', noise, sid.Var1(s), sid.Var1(s)), '\t'));
    catch
        warning('Could not import pair %d', s);
    end
end

has_data = any(rsn_cosim_retest,2) & any(~isnan(rsn_wuc_retest),2);

rsn_cosim_retest = rsn_cosim_retest(has_data,:);
rsn_wuc_retest = rsn_wuc_retest(has_data,:);



% import between subject metrics

sid = readtable('../../resources/paired_retest_iid_sid.csv', 'ReadVariableNames',false);
task_wuc = zeros(height(sid), n_roi);
for s = 1:height(sid)
    try
        task_wuc(s,:) = diag(readmatrix(sprintf('../../derivatives/retest/hcp_glm_msmall_grayord_spm/bsc/%s_betas/cosine/%d_v_%d_wuc.tsv',noise,sid.Var1(s),sid.Var2(s)),'FileType','text'));
    catch
        warning('Could not import pair %d', s);
    end
end
for s = 1:height(sid)
    % Some distance matrices are so noise dominated that their test-retest
    % reliability does not produce a valid RDM whitening matrix. We set
    % those to nans here. If we consider the residual non-imaginary
    % subjects for these regions we'll have biased estimates, but nans make
    % these easy to keep track of so we can mask them out later
    nan_regions = imag(task_wuc(s,:)) ~= 0;
    task_wuc(s, nan_regions) = nan;
end

task_cosim = zeros(height(sid), n_roi);
for s = 1:height(sid)
    try
        task_cosim(s,:) = balanced_mean_op*dlmread(sprintf('../../derivatives/retest/hcp_glm_msmall_grayord_spm/bsc/%s_betas/cosine/%d_v_%d_cosim.tsv', noise, sid.Var1(s), sid.Var2(s)), '\t');
    catch
        warning('Could not import pair %d', s);
    end
end

has_data = any(task_cosim,2) & any(~isnan(task_wuc),2);

task_cosim = task_cosim(has_data,:);
task_wuc = task_wuc(has_data,:);

rsn_wuc = zeros(height(sid), n_roi);
for s = 1:height(sid)
    try
        rsn_wuc(s,:) = readmatrix(sprintf('../../derivatives/retest/restingstate/hcp25/bsc/%s_betas/cosine/%d_v_%d_wuc.tsv',noise,sid.Var1(s),sid.Var2(s)),'FileType','text');
    catch
        warning('Could not import pair %d', s);
    end
end
for s = 1:height(sid)
    % Some distance matrices are so noise dominated that their test-retest
    % reliability does not produce a valid RDM whitening matrix. We set
    % those to nans here. If we consider the residual non-imaginary
    % subjects for these regions we'll have biased estimates, but nans make
    % these easy to keep track of so we can mask them out later
    nan_regions = imag(rsn_wuc(s,:)) ~= 0;
    rsn_wuc(s, nan_regions) = nan;
end

rsn_cosim = zeros(height(sid), n_roi);
for s = 1:height(sid)
    try
        rsn_cosim(s,:) = mean(dlmread(sprintf('../../derivatives/retest/restingstate/hcp25/bsc/%s_betas/cosine/%d_v_%d_cosim.tsv', noise, sid.Var1(s), sid.Var2(s)), '\t'));
    catch
        warning('Could not import pair %d', s);
    end
end

has_data = any(rsn_cosim,2) & any(~isnan(rsn_wuc),2);

rsn_cosim = rsn_cosim(has_data,:);
rsn_wuc = rsn_wuc(has_data,:);


%% Plot bargraphs

f1 = figure(97);
f2 = figure(98);
lines = colormap('lines');
lines_dark = tanh(atanh(2*(lines - 0.5)) - 0.3)/2 + 0.5;
lines_darkest = tanh(atanh(2*(lines - 0.5)) - 0.8)/2 + 0.5;

colors = config.matlab_disp_scheme.color_light([5,4,2,3,1],:);
%colors(4:5,:) = [colors(4,:); colors(4,:)];
colors_dark = tanh(atanh(2*(colors - 0.5)) - 0.3)/2 + 0.5;
colors_darkest = tanh(atanh(2*(colors - 0.5)) - 0.8)/2 + 0.5;

clf
w = 56;
t0 = tiledlayout(f1,2,w,'Padding','none','TileSpacing','tight');
t1 = tiledlayout(f2,2,w,'Padding','none','TileSpacing','tight');
s1 = 18;
s2 = 11;
s3 = 13;

ax1 = nexttile(t0);
ax1.Layout.TileSpan = [1,s1]
cla
obs = {task_topo_r_mz, task_topo_r_dz, task_topo_r_fs, task_topo_r_hs, task_topo_r_unr};
yl = [0,0];
for i = 1:size(task_topo_clusters,2)
    hold on;
    bar(i, task_topo_clusters(:,i),'FaceColor', colors(i,:), 'FaceAlpha', 0.5);
    violinplot(obs{i}, 'x',i, ...
        'pointsize', 3, 'facecolor', colors(i,:), 'edgecolor', colors_dark(i,:), ...
        'vwidth', 0.66);
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    h = errorbar(i, task_topo_clusters(i),...
        task_topo_clusters(i) - task_topo_clusters_CI(i,1),task_topo_clusters(i) - task_topo_clusters_CI(i,2), ...
        'LineStyle','none','color',colors_darkest(i,:),'linewidth',2);
end
xlim([0.5,i+0.5])
ylim(yl);
title({'Task'},'FontWeight','bold','fontsize',fontsize); 
subtitle('Topography','fontsize',fontsize)
set(gca,'FontSize',fontsize+2,'XTickLabels',[]);
ylabel({'Mean Regional Similarity',['(cos\theta', char(177), ' CI_{95})']});
grid on
box off
yl1 = ylim;

ax2 = nexttile(t1);
ax2.Layout.TileSpan = [1,s1];
cla
obs = {rsn_topo_r_mz, rsn_topo_r_dz, rsn_topo_r_fs, rsn_topo_r_hs, rsn_topo_r_unr};
yl = [0,0];
for i = 1:size(rsn_topo_clusters,2)
    hold on;
    bar(i, rsn_topo_clusters(:,i),'FaceColor', colors(i,:), 'FaceAlpha', 0.5);
    violinplot(obs{i}, 'x',i, ...
        'pointsize', 3, 'facecolor', colors(i,:), 'edgecolor', colors_dark(i,:), ...
        'vwidth', 0.66);
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    h = errorbar(i, rsn_topo_clusters(i),...
        rsn_topo_clusters(i) - rsn_topo_clusters_CI(i,1),rsn_topo_clusters(i) - rsn_topo_clusters_CI(i,2), ...
        'LineStyle','none','color',colors_darkest(i,:),'linewidth',2);
end
xlim([0.5,i+0.5])
ylim(yl);
title({'RSN'},'FontWeight','bold','fontsize',fontsize); 
subtitle('Topography','fontsize',fontsize)
ylabel({'Mean Regional Similarity',['(cos\theta', char(177), ' CI_{95})']});
set(gca,'FontSize',fontsize+2,'XTickLabels',[]);
grid on
box off
yl2 = ylim;

ax3 = nexttile(t0);
ax3.Layout.Tile = w+1;
ax3.Layout.TileSpan = [1,s1];
cla
obs = {task_geom_r_mz, task_geom_r_dz, task_geom_r_fs, task_geom_r_hs, task_geom_r_unr};
yl = [0,0];
for i = 1:size(task_geom_clusters,2)
    hold on;
    bar(i, task_geom_clusters(:,i),'FaceColor', colors(i,:), 'FaceAlpha', 0.5);
    violinplot(obs{i}, 'x',i, ...
        'pointsize', 3, 'facecolor', colors(i,:), 'edgecolor', colors_dark(i,:), ...
        'vwidth', 0.66);
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    h = errorbar(i, task_geom_clusters(i),...
        task_geom_clusters(i) - task_geom_clusters_CI(i,1), task_geom_clusters(i) - task_geom_clusters_CI(i,2), ...
        'LineStyle','none','color',colors_darkest(i,:),'linewidth',2);
end
xlim([0.5,i+0.5])
ylim(yl);
subtitle('Geometry','fontsize',fontsize)
set(gca,'XTick',1:size(task_geom_clusters,2), ...
    'XTickLabels',{'Twins (MZ)','Twins (DZ)','Siblings (Full)','Siblings (Half)','Unrelated'}, ...
    'FontSize',fontsize+2,'XTickLabelRotation', 90);
ylabel({'Mean Regional Similarity',['(WUC', char(177), ' CI_{95})']});
grid on
box off
yl3 = ylim;

ax4 = nexttile(t1);
ax4.Layout.Tile = w+1;
ax4.Layout.TileSpan = [1,s1];
cla
obs = {rsn_geom_r_mz, rsn_geom_r_dz, rsn_geom_r_fs, rsn_geom_r_hs, rsn_geom_r_unr};
yl = [0,0];
for i = 1:size(rsn_geom_clusters,2)
    hold on;
    bar(i, rsn_geom_clusters(:,i),'FaceColor', colors(i,:), 'FaceAlpha', 0.5);
    violinplot(obs{i}, 'x',i, ...
        'pointsize', 3, 'facecolor', colors(i,:), 'edgecolor', colors_dark(i,:), ...
        'vwidth', 0.66);
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    h = errorbar(i, rsn_geom_clusters(i),...
        rsn_geom_clusters(i) - rsn_geom_clusters_CI(i,1), rsn_geom_clusters(i) - rsn_geom_clusters_CI(i,2), ...
        'LineStyle','none','color',colors_darkest(i,:),'linewidth',2);
end
xlim([0.5,i+0.5])
ylim(yl);
title({'Geometry'},'FontWeight','normal','fontsize',fontsize); 
set(gca,'XTick',1:size(rsn_geom_clusters,2), ...
    'XTickLabels',{'Twins (MZ)','Twins (DZ)','Siblings (Full)','Siblings (Half)','Unrelated'}, ...
    'FontSize',fontsize+2,'XTickLabelRotation', 90);
ylabel({'Mean Regional Similarity',['(WUC', char(177), ' CI_{95})']});
grid on
box off
yl4 = ylim;


%{
sgtitle(f1,{'Family Clusters'},'FontSize',fontsize+4,'FontWeight','BOLD');

pos = get(f1,'Position');
set(f1,'Position',[pos(1:2),200,650])


sgtitle(f2,{'Family Clusters'},'FontSize',fontsize+4,'FontWeight','BOLD');

pos = get(f2,'Position');
set(f2,'Position',[pos(1:2),200,650])
%}

disp('tSNR')
disp('Task Topography:')
disp([task_topo_clusters'./diff(task_topo_clusters_CI,[],2), task_geom_clusters'./diff(task_geom_clusters_CI,[],2)])

disp('Task Geometry:')
disp([task_topo_clusters'./diff(task_topo_clusters_CI,[],2), task_geom_clusters'./diff(task_geom_clusters_CI,[],2)])

disp('RSN Topography:')
disp([rsn_topo_clusters'./diff(rsn_topo_clusters_CI,[],2), rsn_geom_clusters'./diff(rsn_geom_clusters_CI,[],2)])

disp('RSN Geometry:')
disp([rsn_topo_clusters'./diff(rsn_topo_clusters_CI,[],2), rsn_geom_clusters'./diff(rsn_geom_clusters_CI,[],2)])

%% Plot test-retest reliability of geometry and topography for tasks and RSNs
%{
f3 = figure(101); 
f4 = figure(102); 
lines = colormap('lines');
lines_dark = tanh(atanh(2*(lines - 0.5)) - 0.3)/2 + 0.5;
lines_darkest = tanh(atanh(2*(lines - 0.5)) - 0.8)/2 + 0.5;

clf
t0 = tiledlayout(f3,2,1,'Padding','none','TileSpacing','compact');
t1 = tiledlayout(f4,2,1,'Padding','none','TileSpacing','compact');
%}
ax5 = nexttile(t0);
ax5.Layout.TileSpan = [1,s2];
ax5.Layout.Tile = 11;
cla
bar([mean(task_cosim_retest(:))], 'FaceColor', [0.5,0.5,0.5], 'FaceAlpha', 0.5);
hold on;
violinplot({mean(task_cosim_retest,2)'}, ...
    'pointsize', 3, 'facecolor', [0.5,0.5,0.5], 'edgecolor', [0.3,0.3,0.3], ...
    'vwidth', 0.66);
%title({'Task'},'FontWeight','bold','fontsize',fontsize); 
%subtitle('Topography','fontsize',fontsize)
set(gca,'FontSize',fontsize+2,'XTickLabels',[],'XTickLabelRotation',0);
set(get(gca,'YAxis'),'visible','off')
%ylabel({'Mean Regional Similarity',['(cos\theta', char(177), ' CI_{95})']});
grid on
box off
yl5 = ylim;
yline(ax5,mean(task_cosim_retest(:)))
yline(ax1,mean(task_cosim_retest(:)))

ax6 = nexttile(t1);
ax6.Layout.TileSpan = [1,s2];
ax6.Layout.Tile = 11;
cla
bar([mean(rsn_cosim_retest(:))], 'FaceColor',  [0.5,0.5,0.5], 'FaceAlpha', 0.5);
hold on;
violinplot({mean(rsn_cosim_retest,2)'}, ...
    'pointsize', 3, 'facecolor',  [0.5,0.5,0.5], 'edgecolor',  [0.3,0.3,0.3], ...
    'vwidth', 0.66);
%title({'RSN'},'FontWeight','bold','fontsize',fontsize); 
%subtitle('Topography','fontsize',fontsize)
set(gca,'FontSize',fontsize+2,'XTickLabels',[],'XTickLabelRotation',0);
set(get(gca,'YAxis'),'visible','off')
%ylabel({'Mean Regional Similarity',['(cos\theta', char(177), ' CI_{95})']});
grid on
box off
yl6 = ylim;
yline(ax6,mean(rsn_cosim_retest(:)))
yline(ax2,mean(rsn_cosim_retest(:)))


ax7 = nexttile(t0);
ax7.Layout.Tile = ax3.Layout.Tile + ax3.Layout.TileSpan(2) - 8;
ax7.Layout.TileSpan = [1,s2];
cla
bar([nanmean(task_wuc_retest(:))], 'FaceColor', [0.5,0.5,0.5], 'FaceAlpha', 0.5);
hold on;
violinplot({nanmean(task_wuc_retest,2)'}, ...
    'pointsize', 3, 'facecolor', [0.5,0.5,0.5], 'edgecolor', [0.3,0.3,0.3], ...
    'vwidth', 0.66);
%title({'Geometry'},'FontWeight','normal'); 
set(gca,'FontSize',fontsize+2,'XTickLabels',{'Test-Retest'},'XTickLabelRotation',90);
set(get(gca,'YAxis'),'visible','off')
%ylabel({'Mean Regional Similarity',['(WUC', char(177), ' CI_{95})']});
grid on
box off
yl7 = ylim;
yline(ax7,nanmean(task_wuc_retest(:)))
yline(ax3,nanmean(task_wuc_retest(:)))

ax8 = nexttile(t1);
ax8.Layout.Tile = ax4.Layout.Tile + ax4.Layout.TileSpan(2) - 8;
ax8.Layout.TileSpan = [1,s2];
cla
bar([nanmean(rsn_wuc_retest(:))], 'FaceColor', [0.5,0.5,0.5], 'FaceAlpha', 0.5);
hold on;
violinplot({nanmean(rsn_wuc_retest,2)'}, ...
    'pointsize', 3, 'facecolor', [0.5,0.5,0.5], 'edgecolor', [0.3,0.3,0.3], ...
    'vwidth', 0.66);
%title({'Geometry'},'FontWeight','normal'); 
set(gca,'FontSize',fontsize+2,'XTickLabels',{'Test-Retest'},'XTickLabelRotation',90);
set(get(gca,'YAxis'),'visible','off')
%ylabel({'Mean Regional Similarity',['(WUC', char(177), ' CI_{95})']});
grid on
box off
yl8 = ylim;
yline(ax8,nanmean(rsn_wuc_retest(:)))
yline(ax4,nanmean(rsn_wuc_retest(:)))
%{
pos = get(f3,'Position');
set(f3,'Position',[pos(1:2),79,614]);

pos = get(f4,'Position');
set(f4,'Position',[pos(1:2),79,614]);

sgtitle(f3,'Test-Retest Reliability','FontSize',fontsize+4,'FontWeight','bold')
sgtitle(f4,'Test-Retest Reliability','FontSize',fontsize+4,'FontWeight','bold')
%}
yla = [min([yl1,yl2,yl5,yl6]), max([yl1,yl2,yl5,yl6])];
ylb = [min([yl3,yl4,yl7,yl8]), max([yl3,yl4,yl7,yl8])];

for ax = [ax1,ax2,ax5,ax6]
    set(ax,'YLim',yla);
end
for ax = [ax3,ax4,ax7,ax8]
    set(ax,'YLim',ylb);
end
%{
export_fig(f1,sprintf('panels_%s/task_family_clusters.png',noise),'-transparent','-r300');
export_fig(f2,sprintf('panels_%s/rsn_family_clusters.png',noise),'-transparent','-r300');
export_fig(f3,sprintf('panels_%s/task_test_retest_reliability.png',noise),'-transparent','-r300');
export_fig(f4,sprintf('panels_%s/rsn_test_retest_reliability.png',noise),'-transparent','-r300');
%}
%% plot ranks
%{
f5 = figure(99);
f6 = figure(100);
t0 = tiledlayout(f5,2,2,'Padding','none','TileSpacing','compact');
t1 = tiledlayout(f6,2,2,'Padding','none','TileSpacing','compact');
%}

ax9 = nexttile(t0);
ax9.Layout.Tile = ax5.Layout.Tile + ax5.Layout.TileSpan(2) - 2;
ax9.Layout.TileSpan = [1,s3];
cla
yl = [0,0];
task_topo_rank = rankdata([task_topo_r_mz(:); task_topo_r_dz(:)]);
colors_ = colors(1:2,:);
colors_dark_ = colors_dark(1:2,:);
n1 = length(task_topo_r_mz);
n2 = length(task_topo_r_dz);
y = {task_topo_rank(1:n1), task_topo_rank(n1+1:end)};
%y_ci = [prctile(task_geom_rank(1:n1),[2.5,97.5]), prctile(task_geom_rank(n1+1:end),[2.5,97.5])];
for i = 1:size(y,2)
    hold on;
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    bar(i,mean(y{i}),'FaceColor', colors(i,:), 'FaceAlpha', 0.5);
    h = violinplot(y(:,i), 'x', i, 'pointsize', 3, 'facecolor', colors(i,:), 'edgecolor', colors_dark(i,:), ...
        'vwidth', 0.66);
end
xlim([0.5,i+0.5])
ylim(yl);
ngroups = size(y,1);
nbars = size(y,2);
title({'Genetics'},'FontWeight','bold'); 
subtitle({'Topo'},'FontWeight','normal');
set(gca,'XTick',1:size(y,2),'XTickLabels',{'MZ','DZ'},'FontSize',fontsize+2,'XTickLabelRotation',90);
ylabel('Similarity Rank');
grid on
box off
yl9 = ylim;

ax10 = nexttile(t1);
ax10.Layout.Tile = ax6.Layout.Tile + ax6.Layout.TileSpan(2) - 2;
ax10.Layout.TileSpan = [1,s3];
cla
yl = [0,0];
rsn_topo_rank = rankdata([rsn_topo_r_mz(:); rsn_topo_r_dz(:)]);
n1 = length(rsn_topo_r_mz);
n2 = length(rsn_topo_r_dz);
y = {rsn_topo_rank(1:n1), rsn_topo_rank(n1+1:end)};
for i = 1:size(y,2)
    hold on;
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    bar(i,mean(y{i}),'FaceColor', colors_(i,:), 'FaceAlpha', 0.5);
    h = violinplot(y(:,i), 'x', i, 'pointsize', 3, 'facecolor', colors_(i,:), 'edgecolor', colors_dark_(i,:), ...
        'vwidth', 0.66);
end
xlim([0.5,i+0.5])
ylim(yl);
ngroups = size(y,1);
nbars = size(y,2);
title({'Genetics'},'FontWeight','bold'); 
subtitle({'Topo'},'FontWeight','normal');
set(gca,'XTick',1:size(y,2),'XTickLabels',{'MZ','DZ'},'FontSize',fontsize+2,'XTickLabelRotation',90);
ylabel('Similarity Rank');
grid on
box off
yl10 = ylim;



ax11 = nexttile(t0);
ax11.Layout.Tile = ax9.Layout.Tile + ax9.Layout.TileSpan(2) - 6;
ax11.Layout.TileSpan = [1,s3];
cla
yl = [0,0];
task_geom_rank = rankdata([task_geom_r_mz(:); task_geom_r_dz(:)]);
n1 = length(task_geom_r_mz);
n2 = length(task_geom_r_dz);
y = {task_geom_rank(1:n1), task_geom_rank(n1+1:end)};
%y_ci = [prctile(task_geom_rank(1:n1),[2.5,97.5]), prctile(task_geom_rank(n1+1:end),[2.5,97.5])];
for i = 1:size(y,2)
    hold on;
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    bar(i,mean(y{i}),'FaceColor', colors_(i,:), 'FaceAlpha', 0.5);
    h = violinplot(y(:,i), 'x', i, 'pointsize', 3, 'facecolor', colors_(i,:), 'edgecolor', colors_dark_(i,:), ...
        'vwidth', 0.66);
end
xlim([0.5,i+0.5])
ylim(yl);
ngroups = size(y,1);
nbars = size(y,2);
title({''},'FontWeight','bold'); 
subtitle({'Geo'},'FontWeight','normal');
set(gca,'XTick',1:size(y,2),'XTickLabels',{'MZ','DZ'},'FontSize',fontsize+2,'XTickLabelRotation',90);
set(get(gca,'YAxis'),'Visible','off')
grid on
box off
yl11 = ylim;


ax12 = nexttile(t1);
ax12.Layout.Tile = ax10.Layout.Tile + ax10.Layout.TileSpan(2) - 6;
ax12.Layout.TileSpan = [1,s3];
cla
yl = [0,0];
rsn_geom_rank = rankdata([rsn_geom_r_mz(:); rsn_geom_r_dz(:)]);
n1 = length(rsn_geom_r_mz);
n2 = length(rsn_geom_r_dz);
y = {rsn_geom_rank(1:n1), rsn_geom_rank(n1+1:end)};
for i = 1:size(y,2)
    hold on;
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    bar(i,mean(y{i}),'FaceColor', colors_(i,:), 'FaceAlpha', 0.5);
    h = violinplot(y(:,i), 'x', i, 'pointsize', 3, 'facecolor', colors_(i,:), 'edgecolor', colors_dark_(i,:), ...
        'vwidth', 0.66);
end
xlim([0.5,i+0.5])
ylim(yl);
ngroups = size(y,1);
nbars = size(y,2);
title({''},'FontWeight','bold'); 
subtitle({'Geo'},'FontWeight','normal'); 
set(gca,'XTick',1:size(y,2),'XTickLabels',{'MZ','DZ'},'FontSize',fontsize+2,'XTickLabelRotation',90);
set(get(gca,'YAxis'),'Visible','off')
grid on
box off
yl12 = ylim;


yl = [min([yl9,yl11]), max([yl9,yl11])];
yl(2) = yl(2)*1.2;
set(ax9,'YLim',yl)
set(ax11,'YLim',yl);

yl = [min([yl10,yl12]), max([yl12,yl10])];
yl(2) = yl(2)*1.2;
set(ax10,'YLim',yl)
set(ax12,'YLim',yl);


ax13 = nexttile(t0);
ax13.Layout.Tile = ax7.Layout.Tile + ax7.Layout.TileSpan(2) - 2;
ax13.Layout.TileSpan = [1,s3];
colors_ = colors(2:3,:);
colors_dark_ = colors_dark(2:3,:);
cla
yl = [0,0];
task_topo_rank = rankdata([task_topo_r_dz(:); task_topo_r_fs_not_dz(:)]);
n1 = length(task_topo_r_dz);
n2 = length(task_topo_r_fs_not_dz);
y = {task_topo_rank(1:n1), task_topo_rank(n1+1:end)};
for i = 1:size(y,2)
    hold on;
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    bar(i,mean(y{i}),'FaceColor', colors_(i,:), 'FaceAlpha', 0.5);
    h = violinplot(y(:,i), 'x', i, 'pointsize', 3, 'facecolor', colors_(i,:), 'edgecolor', colors_dark_(i,:), ...
        'vwidth', 0.66);
end
xlim([0.5,i+0.5])
ylim(yl);
ngroups = size(y,1);
nbars = size(y,2);
title({'Environment'},'FontWeight','bold');
subtitle({'Topo'},'FontWeight','normal'); 
set(gca,'XTick',1:size(y,2),'XTickLabels',{'Twins (DZ)','Sublings (Full)'},'FontSize',fontsize+2,'XTickLabelRotation',90);
ylabel('Similarity Rank');
grid on
box off
yl13 = ylim;

ax14 = nexttile(t0);
ax14.Layout.Tile = ax13.Layout.Tile + ax13.Layout.TileSpan(2) - 6;
ax14.Layout.TileSpan = [1,s3];
cla
yl = [0,0];
task_geom_rank = rankdata([task_geom_r_dz(:); task_geom_r_fs_not_dz(:)]);
n1 = length(task_geom_r_dz);
n2 = length(task_geom_r_fs_not_dz);
y = {task_geom_rank(1:n1), task_geom_rank(n1+1:end)};
for i = 1:size(y,2)
    hold on;
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    bar(i,mean(y{i}),'FaceColor', colors_(i,:), 'FaceAlpha', 0.5);
    h = violinplot(y(:,i), 'x', i, 'pointsize', 3, 'facecolor', colors_(i,:), 'edgecolor', colors_dark_(i,:), ...
        'vwidth', 0.66);
end
xlim([0.5,i+0.5])
ylim(yl);
ngroups = size(y,1);
nbars = size(y,2);
title({' '},'FontWeight','bold');
subtitle({'Geo'},'FontWeight','normal'); 
set(gca,'XTick',1:size(y,2),'XTickLabels',{'Twins (DZ)','Siblings (Full)'},'FontSize',fontsize+2,'XTickLabelRotation',90);
ylabel('Similarity Rank');
grid on
box off
set(get(gca,'YAxis'),'Visible','off');
yl14 = ylim;

yl = [min([yl13,yl14]), max([yl13,yl14])];
yl(2) = yl(2)*1.2;
set(ax13,'YLim',yl)
set(ax14,'YLim',yl);


ax15 = nexttile(t1);
ax15.Layout.Tile = ax8.Layout.Tile + ax8.Layout.TileSpan(2) - 2;
ax15.Layout.TileSpan = [1,s3];
cla
yl = [0,0];
rsn_topo_rank = rankdata([rsn_topo_r_dz(:); rsn_topo_r_fs_not_dz(:)]);
n1 = length(rsn_topo_r_dz);
n2 = length(rsn_geom_r_fs_not_dz);
y = {rsn_topo_rank(1:n1), rsn_topo_rank(n1+1:end)};
for i = 1:size(y,2)
    hold on;
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    bar(i,mean(y{i}),'FaceColor', colors_(i,:), 'FaceAlpha', 0.5);
    h = violinplot(y(:,i), 'x', i, 'pointsize', 3, 'facecolor', colors_(i,:), 'edgecolor', colors_dark_(i,:), ...
        'vwidth', 0.66);
end
xlim([0.5,i+0.5])
ylim(yl);
ngroups = size(y,1);
nbars = size(y,2);
title({'Environment'},'FontWeight','bold');
subtitle({'Topo'},'FontWeight','normal'); 
set(gca,'XTick',1:size(y,2),'XTickLabels',{'Twins (DZ)','Siblings (Full)'},'FontSize',fontsize+2,'XTickLabelRotation',90);
ylabel('Similarity Rank');
grid on
box off
yl15 = ylim;

ax16 = nexttile();
ax16.Layout.Tile = ax15.Layout.Tile + ax15.Layout.TileSpan(2) - 6;
ax16.Layout.TileSpan = [1,s3];
cla
yl = [0,0];
rsn_geom_rank = rankdata([rsn_geom_r_dz(:); rsn_geom_r_fs_not_dz(:)]);
n1 = length(rsn_geom_r_dz);
n2 = length(rsn_geom_r_fs_not_dz);
y = {rsn_geom_rank(1:n1), rsn_geom_rank(n1+1:end)};
%y_ci = [prctile(task_geom_rank(1:n1),[2.5,97.5]), prctile(task_geom_rank(n1+1:end),[2.5,97.5])];
for i = 1:size(y,2)
    hold on;
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    bar(i,mean(y{i}),'FaceColor', colors_(i,:), 'FaceAlpha', 0.5);
    h = violinplot(y(:,i), 'x', i, 'pointsize', 3, 'facecolor', colors_(i,:), 'edgecolor', colors_dark_(i,:), ...
        'vwidth', 0.66);
end
xlim([0.5,i+0.5])
ylim(yl);
ngroups = size(y,1);
nbars = size(y,2);
title({' '},'FontWeight','bold');
subtitle({'Geo'},'FontWeight','normal'); 
set(gca,'XTick',1:size(y,2),'XTickLabels',{'Twins (DZ)','Siblings (Full)'},'FontSize',fontsize+2,'XTickLabelRotation',90);
ylabel('Similarity Rank');
grid on
box off
set(get(gca,'YAxis'),'Visible','off')
yl16 = ylim;

yl = [min([yl15,yl16]), max([yl15,yl16])];
yl(2) = yl(2)*1.2;
set(ax15,'YLim',yl15)
set(ax16,'YLim',yl16);
%{
pos = get(f5,'Position');
set(f5,'Position',[pos(1:2),200,650]);

pos = get(f6,'Position');
set(f6,'Position',[pos(1:2),200,650]);

export_fig(f5,sprintf('panels_%s/task_ranks.png',noise),'-transparent','-r300');
export_fig(f6,sprintf('panels_%s/rsn_ranks.png',noise),'-transparent','-r300');
%}
%% Nonparametric tests of heritability
disp('Task Topography')
x = task_topo_r_mz;
y = task_topo_r_dz;
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P,H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

disp('Task Geometry')
x = task_geom_r_mz;
y = task_geom_r_dz;
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P,H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

disp('RSN Topography')
x = rsn_topo_r_mz;
y = rsn_topo_r_dz;
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P,H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

disp('RSN Geometry')
x = rsn_geom_r_mz;
y = rsn_geom_r_dz;
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P,H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

%% Nonparmaetric interaction tests of mz vs. dz x geometry vs. topography
nx = length(task_topo_r_mz);
ny = length(task_topo_r_dz);
grp = [1*ones(nx,1); -1*ones(ny,1)];

topo = [task_topo_r_mz; task_topo_r_dz];
geom = [task_geom_r_mz; task_geom_r_dz];

has_data = ~isnan(topo) & ~isnan(geom);

topo = rankdata(topo(has_data));
geom = rankdata(geom(has_data));
grp = grp(has_data);

genes_task_dmz = topo(grp > 0) - geom(grp > 0);
genes_task_ddz = topo(grp < 0) - geom(grp < 0);

disp('MZ vs. DZ x Geometry vs. Topography (task):')
[P,H,STATS] = ranksum(genes_task_dmz,genes_task_ddz,'tail','right')
U = STATS.ranksum - length(genes_task_dmz)*(length(genes_task_dmz) + 1)/2
AUC = U/(length(genes_task_dmz)*length(genes_task_ddz))




nx = length(rsn_topo_r_mz);
ny = length(rsn_topo_r_dz);
grp = [1*ones(nx,1); -1*ones(ny,1)];

topo = [rsn_topo_r_mz; rsn_topo_r_dz];
geom = [rsn_geom_r_mz; rsn_geom_r_dz];

has_data = ~isnan(topo) & ~isnan(geom);

topo = rankdata(topo(has_data));
geom = rankdata(geom(has_data));
grp = grp(has_data);

genes_rsn_dmz = topo(grp > 0) - geom(grp > 0);
genes_rsn_ddz = topo(grp < 0) - geom(grp < 0);

disp('MZ vs. DZ x Geometry vs. Topography (RSN):')
[P,H,STATS] = ranksum(genes_task_dmz,genes_rsn_ddz,'tail','right')
U = STATS.ranksum - length(genes_rsn_dmz)*(length(genes_rsn_dmz) + 1)/2
AUC = U/(length(genes_rsn_dmz)*length(genes_rsn_ddz))

%% Nonparametric tests of dz vs. fs environment
P = zeros(4,1);

disp('Task Topography')
x = task_topo_r_dz;
y = task_topo_r_fs_not_dz;
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P(1),H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

disp('Task Geometry')
x = task_geom_r_dz;
y = task_geom_r_fs_not_dz;
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P(2),H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

disp('RSN Topography')
x = rsn_topo_r_dz;
y = rsn_topo_r_fs_not_dz;
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P(3),H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

disp('RSN Geometry')
x = rsn_geom_r_dz;
y = rsn_geom_r_fs_not_dz;
nx = sum(~isnan(x));
ny = sum(~isnan(y));
[P(4),H,STATS] = ranksum(x, y,'tail','right')
U = STATS.ranksum - nx*(nx + 1)/2
AUC = U/(nx*ny)

holm_sidak(P,0.05)

%% Nonparmaetric interaction tests of dz vs. fs x geometry vs. topography

dz_topo = task_topo_r_dz;
fs_topo = task_topo_r_fs_not_dz;
dz_geom = task_geom_r_dz;
fs_geom = task_geom_r_fs_not_dz;

nx = length(dz_topo);
ny = length(fs_topo);
grp = [1*ones(nx,1); -1*ones(ny,1)];

topo = [dz_topo; fs_topo];
geom = [dz_geom; fs_geom];

has_data = ~isnan(topo) & ~isnan(geom);

topo = rankdata(topo(has_data));
geom = rankdata(geom(has_data));
grp = grp(has_data);

env_task_ddz = geom(grp > 0) - topo(grp > 0);
env_task_dfs = geom(grp < 0) - topo(grp < 0);

disp('DZ vs. FS x Geometry vs. Topography (Task):')
[P,H,STATS] = ranksum(env_task_ddz,env_task_dfs,'tail','right')
U = STATS.ranksum - length(env_task_ddz)*(length(env_task_ddz) + 1)/2
AUC = U/(length(env_task_ddz)*length(env_task_dfs))


dz_topo = rsn_topo_r_dz;
fs_topo = rsn_topo_r_fs_not_dz;
dz_geom = rsn_geom_r_dz;
fs_geom = rsn_geom_r_fs_not_dz;

nx = length(dz_topo);
ny = length(fs_topo);
grp = [1*ones(nx,1); -1*ones(ny,1)];

topo = [dz_topo; fs_topo];
geom = [dz_geom; fs_geom];

has_data = ~isnan(topo) & ~isnan(geom);

topo = rankdata(topo(has_data));
geom = rankdata(geom(has_data));
grp = grp(has_data);

env_rsn_ddz = geom(grp > 0) - topo(grp > 0);
env_rsn_dfs = geom(grp < 0) - topo(grp < 0);

disp('DZ vs. FS x Geometry vs. Topography (RSN):')
[P,H,STATS] = ranksum(env_rsn_ddz,env_rsn_dfs,'tail','right')
U = STATS.ranksum - length(env_rsn_ddz)*(length(env_rsn_ddz) + 1)/2
AUC = U/(length(env_rsn_ddz)*length(env_rsn_dfs))

%% Plot task x geom genetic interactions 
%{
f5 = figure(103);
t0 = tiledlayout(f5,2,1,'Padding','none','TileSpacing','compact');
%}
ax17 = nexttile(t0);
ax17.Layout.Tile = ax11.Layout.Tile + ax11.Layout.TileSpan(2) + 1;
ax17.Layout.TileSpan = [1,s3];
colors_ = colors(1:2,:);
colors_dark_ = colors_dark(1:2,:);
cla
y = {genes_task_dmz, genes_task_ddz};
yl = [0,0];
for i = 1:size(y,2)
    hold on;
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    bar(i,mean(y{i}),'FaceColor', colors_(i,:), 'FaceAlpha', 0.5);
    h = violinplot(y(:,i), 'x', i, 'pointsize', 3, 'facecolor', colors_(i,:), 'edgecolor', colors_dark_(i,:), ...
        'vwidth', 0.66);
end
xlim([0.5,i+0.5])
ylim(yl);
ngroups = size(y,1);
nbars = size(y,2);
title({'Genes'},'FontWeight','normal'); 
set(gca,'XTick',1:size(y,2),'XTickLabels',{'MZ','DZ'},'FontSize',fontsize+2,'XTickLabelRotation',90);
ylabel({'Topography - Geometry','(Ranks)'});
grid on
box off
yl = ylim;
set(gca,'YLim',[yl(1),yl(2)*1.2]);
yl17 = ylim;


ax18 = nexttile(t0);
ax18.Layout.Tile = ax14.Layout.Tile + ax14.Layout.TileSpan(2) + 1;
ax18.Layout.TileSpan = [1,s3];
colors_ = colors(2:3,:);
colors_dark_ = colors_dark(2:3,:);
cla
y = {env_task_ddz, env_task_dfs};
yl = [0,0];
for i = 1:size(y,2)
    hold on;
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    bar(i,mean(y{i}),'FaceColor', colors_(i,:), 'FaceAlpha', 0.5);
    h = violinplot(y(:,i), 'x', i, 'pointsize', 3, 'facecolor', colors_(i,:), 'edgecolor', colors_dark_(i,:), ...
        'vwidth', 0.66);
end
xlim([0.5,i+0.5])
ylim(yl);
ngroups = size(y,1);
nbars = size(y,2);
title({'Env'},'FontWeight','normal'); 
set(gca,'XTick',1:size(y,2),'XTickLabels',{'Twins (DZ)','Siblings (Full)'},'FontSize',fontsize+2,'XTickLabelRotation',90);
ylabel({'Topography - Geometry','(Ranks)'});
grid on
box off
yl = ylim;
set(gca,'YLim',[yl(1),yl(2)*1.2]);
yl18 = ylim;

%{
pos = get(gcf,'Position');
set(gcf,'Position',[pos(1:2),140,625]);

f6 = figure(104);
t1 = tiledlayout(f6,2,1,'Padding','none','TileSpacing','compact');
%}

ax19 = nexttile(t1);
ax19.Layout.Tile = ax12.Layout.Tile + ax12.Layout.TileSpan(2) + 1;
ax19.Layout.TileSpan = [1,s3];
colors_ = colors(1:2,:);
colors_dark_ = colors_dark(1:2,:);
cla
y = {genes_rsn_dmz, genes_rsn_ddz};
yl = [0,0];
for i = 1:size(y,2)
    hold on;
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    bar(i,mean(y{i}),'FaceColor', colors_(i,:), 'FaceAlpha', 0.5);
    h = violinplot(y(:,i), 'x', i, 'pointsize', 3, 'facecolor', colors_(i,:), 'edgecolor', colors_dark_(i,:), ...
        'vwidth', 0.66);
end
xlim([0.5,i+0.5])
ylim(yl);
ngroups = size(y,1);
nbars = size(y,2);
title({'Genes'},'FontWeight','normal'); 
set(gca,'XTick',1:size(y,2),'XTickLabels',{'MZ','DZ'},'FontSize',fontsize+2,'XTickLabelRotation',90);
ylabel({'Topography - Geometry','(Ranks)'});
grid on
box off
yl = ylim;
set(gca,'YLim',[yl(1),yl(2)*1.2]);
yl17 = ylim;


ax18 = nexttile(t1);
ax18.Layout.Tile = ax16.Layout.Tile + ax16.Layout.TileSpan(2) + 1;
ax18.Layout.TileSpan = [1,s3];
colors_ = colors(2:3,:);
colors_dark_ = colors_dark(2:3,:);
cla
y = {env_rsn_ddz, env_rsn_dfs};
yl = [0,0];
for i = 1:size(y,2)
    hold on;
    this_yl = ylim;
    yl = [min(this_yl(1),yl(1)), max(this_yl(2), yl(2))];
    bar(i,mean(y{i}),'FaceColor', colors_(i,:), 'FaceAlpha', 0.5);
    h = violinplot(y(:,i), 'x', i, 'pointsize', 3, 'facecolor', colors_(i,:), 'edgecolor', colors_dark_(i,:), ...
        'vwidth', 0.66);
end
xlim([0.5,i+0.5])
ylim(yl);
ngroups = size(y,1);
nbars = size(y,2);
title({'Env'},'FontWeight','normal'); 
set(gca,'XTickLabels',{'Twins (DZ)','Siblings (Full)'},'FontSize',fontsize+2,'XTickLabelRotation',90);
ylabel({'Topography - Geometry','(Ranks)'});
grid on
box off
yl = ylim;
set(gca,'YLim',[yl(1),yl(2)*1.2]);
yl18 = ylim;

pos = get(f1,'Position');
set(f1,'Position',[pos(1:2),605,650]);

pos = get(f2,'Position');
set(f2,'Position',[pos(1:2),605,650]);

sgtitle(f1,{'Task Heritability and Environment Effects','',''},'FontSize',fontsize+4,'FontWeight','bold')
sgtitle(f2,{'RSN Heritability and Environment Effects','',''},'FontSize',fontsize+4,'FontWeight','bold')

export_fig(f1,sprintf('panels_%s/task.png',noise),'-transparent','-r300');
export_fig(f2,sprintf('panels_%s/rsn.png',noise),'-transparent','-r300');